feat(qiankun): add MicroAppLink component
umijs/umi pull request #10090
Opened 2022-12-16 11:53 UTC by ice-zjchen

2022-12-23 08:36 UTC, kuitos commented on packages/plugins/libs/qiankun/slave/MicroAppLink.tsx
> +__USE_MODEL__;
这是个啥？

2022-12-23 08:36 UTC, kuitos commented on packages/plugins/libs/qiankun/master/MicroApp.tsx
> +            globalRoutesInfo: {
加俩下划线？别跟个用户自己的配置冲突了

2022-12-23 08:36 UTC, kuitos commented on packages/plugins/libs/qiankun/slave/MicroAppLink.tsx
> +      appRoute.startsWith('/') ? appRoute.slice(1) : appRoute
这个能不能换成必须是 `/` 开头的路径，这样就不用考虑 `./`这种相对路径支持了

2022-12-23 08:36 UTC, kuitos commented on packages/plugins/libs/qiankun/master/MicroApp.tsx
> +              routes: globalSettings.routes,
globalSettings.routes 这个是已经有的吗？

2022-12-23 08:45 UTC, ice-zjchen commented on packages/plugins/libs/qiankun/slave/MicroAppLink.tsx
> +__USE_MODEL__;
引入 `useModel` 的占位符，见：https://github.com/umijs/umi/blob/master/packages/plugins/libs/qiankun/master/MicroApp.tsx#L3

2022-12-26 09:49 UTC, ice-zjchen commented on packages/plugins/libs/qiankun/master/MicroApp.tsx
> +            __globalRoutesInfo: {
@kuitos `__` added

2022-12-26 09:53 UTC, ice-zjchen commented on packages/plugins/libs/qiankun/slave/MicroAppLink.tsx
> +      appRoute.startsWith('/') ? appRoute.slice(1) : appRoute
这个只能运行时判断，直接抛出错误不太好。但可以不支持  `./` ，目前基于是a标签，开发者鼠标hover上去能看到最终生成链接。如果错了，就是错了

2022-12-27 06:48 UTC, ice-zjchen commented on docs/docs/max/micro-frontend.md
> +      <MicroAppLink appName="app1" appRoute="/hello">
done

2022-12-27 06:53 UTC, ice-zjchen commented on packages/plugins/libs/qiankun/slave/MicroAppLink.tsx
> +      appRoute.startsWith('/') ? appRoute.slice(1) : appRoute
改成抛异常了

2022-12-27 08:23 UTC, kuitos requested changes

2022-12-27 08:23 UTC, kuitos commented on packages/plugins/src/qiankun/master.ts
> +        microAppRoutes.push(route);
这里是静态配置才会走，会漏掉动态 patch 进来的 routes。应该在运行时去过滤出 microAppRoute 然后再存起来

2022-12-28 09:44 UTC, ice-zjchen commented on packages/plugins/libs/qiankun/master/masterRuntimePlugin.tsx
> +    // 动态patch的routes存到 masterOptions.microAppRoutes 下以供 MicroAppLink 使用
@kuitos  here stored dynamic patched routes

2022-12-28 11:31 UTC, kuitos reviewed
遗留问题：
1. 使用 yuyanId 模式消费的逻辑还没实现
2. 只记录了 runtime routes，没有静态 routes，应该是这两个要 concat 到一起，然后过滤出微应用关联的路由配置

2022-12-28 12:20 UTC, ice-zjchen commented on packages/plugins/libs/qiankun/slave/MicroAppLink.tsx
> +  // ref: https://github.com/umijs/plugins/pull/866 基于 name 或 appNameKeyAlias 取到 appName 的逻辑
@kuitos  appNameKeyAlias 逻辑在这儿

2022-12-28 12:21 UTC, ice-zjchen commented on packages/plugins/libs/qiankun/master/masterRuntimePlugin.tsx
> +  const microAppRoutes = [].concat(
所有microAppRoutes的逻辑收敛在了这里

2022-12-29 07:55 UTC, kuitos commented on packages/plugins/libs/qiankun/master/masterRuntimePlugin.tsx
> +    routes.filter((r) => r.microApp),
这里不去深度优先遍历一下吗？

2022-12-29 07:55 UTC, kuitos commented on packages/plugins/libs/qiankun/slave/MicroAppLink.tsx
> +  const { masterHistoryType, microAppRoutes, base, appNameKeyAlias } =
appNameKeyAlias 可能是 undefined，要做下非空保护

2023-01-10 13:58 UTC, kuitos approved these changes

2023-01-11 08:04 UTC, PeachScript requested changes

2023-01-11 08:04 UTC, PeachScript commented on packages/plugins/libs/qiankun/master/routeUtils.ts
> +        findLeafRoutes(r?.routes);
`?` 可以去掉了

2023-01-11 08:26 UTC, PeachScript approved these changes
+1

2023-01-11 08:56 UTC, merged