fix(qiankun-plugin): 修复本地研发时热更新报错
umijs/umi pull request #10165
Opened 2022-12-28 09:14 UTC by HiLanXiao

本地研发时设置__QIANKUN_DEVELOPMENT__ 为true

2022-12-28 11:11 UTC, kuitos approved these changes

2022-12-28 11:49 UTC, sorrycc requested changes

2022-12-28 11:49 UTC, sorrycc commented on packages/plugins/src/qiankun/slave.ts
> +    `<script>window.__QIANKUN_DEVELOPMENT__=true</script>
是否应该针对 dev 时才加入 window.__QIANKUN_DEVELOPMENT__=true ？

2022-12-28 12:56 UTC, HiLanXiao commented on packages/plugins/src/qiankun/slave.ts
> +    `<script>window.__QIANKUN_DEVELOPMENT__=true</script>
这个 func 是在 api.addMiddlewares 里消费的，我理解这个只会在本地 dev 触发

2022-12-29 06:18 UTC, sorrycc approved these changes

2022-12-29 06:18 UTC, merged