feat(preset-umi): external dependencies in ssr builder
umijs/umi pull request #10213
Opened 2023-01-05 06:24 UTC by AkaraChen

2023-01-05 06:44 UTC, fz6m commented on packages/preset-umi/src/features/ssr/builder/builder.ts
> +  }
```ts
  function getExternal() {
    const { cwd } = api.paths;
    if (isMonorepo({ root: cwd })) {
      // TODO: 先不考虑 monorepo 的场景，因为可能依赖了其他的子包
      return []
    } else {
      return Object.keys(api.pkg.dependencies || {});
    }
  }
```

代码建议这样改。

`isMonorepo` 的逻辑在 `packages/preset-umi/src/features/monorepo/redirect.ts` 里面，把：

```ts
interface IOpts {
  root: string;
}

const MONOREPO_FILE = ['pnpm-workspace.yaml', 'lerna.json'];
export function isMonorepo(opts: IOpts) {
  const pkgPath = join(opts.root, 'package.json');
  let pkg: Record<string, any> = {};
  try {
    pkg = require(pkgPath);
  } catch (e) {}
  const pkgExist = existsSync(pkgPath);
  return (
    pkgExist &&
    (MONOREPO_FILE.some((file) => {
      return existsSync(join(opts.root, file));
    }) ||
      // npm workspaces
      pkg?.workspaces)
  );
}
```

移动到 `@umijs/utils/src/isMonorepo.ts` 里，从 `src/index.ts` 导出，之后使用这个方法。

另外，`isMonorepo` 在 `packages/preset-umi/src/features/tmpFiles/routes.ts` 还有一处导入，也改一下 import 位置。

2023-01-05 07:42 UTC, fz6m commented on packages/preset-umi/src/features/monorepo/redirect.ts
> +import { isMonorepo } from '@umijs/utils';
合并到上面 `@umijs/utils` 的 import 里。

2023-01-05 07:42 UTC, fz6m commented on packages/preset-umi/src/features/ssr/builder/builder.ts
> +import { isMonorepo } from '@umijs/utils';
合并下 import 。

2023-01-05 07:42 UTC, fz6m commented on packages/preset-umi/src/features/tmpFiles/routes.ts
> +import { isMonorepo } from '@umijs/utils';
合并下 import 。

2023-01-05 07:51 UTC, fz6m commented on packages/preset-umi/src/features/ssr/builder/builder.ts
>    // TODO: external all import from package.json.dependencies
```suggestion
```

2023-01-05 07:52 UTC, fz6m approved these changes

2023-01-05 13:05 UTC, sorrycc requested changes

2023-01-05 13:05 UTC, sorrycc commented on packages/preset-umi/src/features/ssr/builder/builder.ts
> +      return Object.keys(api.pkg.dependencies || {});
devDependencies 也要带上吧。

2023-01-05 13:13 UTC, fz6m commented on packages/preset-umi/src/features/ssr/builder/builder.ts
> +      return Object.keys(api.pkg.dependencies || {});
ssr 的项目在部署的时候应该只需要安装 `dependencies` 里的依赖作为 external ，`devDependencies` 在部署的时候不需要安装。

[pnpm prune](https://pnpm.io/cli/prune) 就是对应的一个切割 node_modules 节省空间的方案。

2023-01-06 03:35 UTC, sorrycc commented on packages/preset-umi/src/features/ssr/builder/builder.ts
> +      return Object.keys(api.pkg.dependencies || {});
我理解这是最佳实践，但用户在用的时候可能不会区分那么细，另外 devDependencies 带上好像也没有副作用。

2023-01-06 03:36 UTC, sorrycc approved these changes

2023-01-06 03:36 UTC, merged