feat: changelog by prs
umijs/umi pull request #10261
Opened 2023-01-10 08:34 UTC by txp1035

## 这个pr主要解决：
1. changelog生成
2. 发布流程优化(发布后自动跳转到发布页面)
## 解决方案：
通过请求releases/notes接口拿到发布的信息，保存进changelog。
## 参考
api使用文档
https://docs.github.com/zh/rest/quickstart?apiVersion=2022-11-28
创建令牌文档
https://docs.github.com/zh/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
日志生成
https://docs.github.com/zh/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release

close #9215

2023-01-10 14:37 UTC, txp1035 commented
代码很好懂，那个权限那块尝试耗时比较久。
看api甚至可以不用打开网页直接本地通过api就可以进行github发布的。但是涉及到写入操作还是要云谦老师这边评估下。
@sorrycc

2023-01-10 15:12 UTC, txp1035 commented
整个release文件虽然有注释隔开各个流程，但是调试的时候可能想跳过打包什么的步骤就要注释一大块代码，是不是把各个流程封装到function，主流程调用function比较清晰一点呢？

2023-01-11 06:19 UTC, xiaohuoni commented
git token 不是一般从配置里面取就可以吗？

2023-01-11 07:15 UTC, txp1035 commented
> git token 不是一般从配置里面取就可以吗？
你说的ssh的那个公钥？和私钥？

2023-01-12 02:35 UTC, sorrycc requested changes

2023-01-12 02:35 UTC, sorrycc commented on scripts/release.ts
> +  const CHANGELOG_PATH = join(PATHS.ROOT, 'CHANGELOG.md');
CHANGELOG.md 改成 TMP_CHANGELOG.md，同时加到 .gitignore 里，以 github release 里的为准，不再仓库里再搞一份。

2023-01-12 02:35 UTC, sorrycc commented on scripts/release.ts
> +  const { releaseNotes } = await githubRelease(version);
1、需要加日志
2、只有正式版发布时才需要生成日志，canary、rc、beta、alpha 都不需要

2023-01-12 05:13 UTC, txp1035 commented on scripts/release.ts
> +  const CHANGELOG_PATH = join(PATHS.ROOT, 'CHANGELOG.md');
其实这个的作用可以提现在放官网，不知道umi需不需要

2023-01-12 05:14 UTC, txp1035 commented on scripts/release.ts
> +  const CHANGELOG_PATH = join(PATHS.ROOT, 'CHANGELOG.md');
https://tr.imtxp.cn/version/version 类似这种效果，每次发版自动更新

2023-01-12 07:47 UTC, sorrycc requested changes
CHANGELOG.md 删下，其他没问题了，等今天发布完再合，我找个小的版本更新验证下。

2023-01-12 07:58 UTC, txp1035 commented
> CHANGELOG.md 删下，其他没问题了，等今天发布完再合，我找个小的版本更新验证下。

好的，CHANGELOG.md换成TMP_CHANGELOG了

2023-01-12 08:07 UTC, sorrycc commented
TMP_CHANGELOG 是本地文件，需要加到 .gitignore 里，github 上的仓库里不应该出现这个文件。

2023-01-12 12:43 UTC, sorrycc commented
冲突了，merge 下 master。

2023-01-12 15:14 UTC, txp1035 commented
> 冲突了，merge 下 master。

merge了

2023-01-13 03:33 UTC, sorrycc approved these changes

2023-01-13 03:33 UTC, merged