fix: 🐛 antd 组件属性 visible 更换为 open
umijs/umi pull request #10296
Opened 2023-01-14 11:31 UTC by huxinfeng

antd 组件属性 `visible` 将在下一个大版本中移除，变更为 `open`
解决控制台报错 bug
<img width="517" alt="image" src="https://user-images.githubusercontent.com/63422671/212469737-5bb0f5ea-a33d-4a2b-9571-b563b34e5822.png">

2023-01-14 13:28 UTC, fz6m commented
小于 4.23.0 才能用 open ，`ant-design-pro` 和 `create-umi-pro`  不满足，要不然就别改这俩项目的文件，如果要改的话，得升一下他们的 antd 依赖版本

2023-01-14 18:16 UTC, huxinfeng commented
> 大于 4.23.0 才能用 open ，`ant-design-pro` 和 `create-umi-pro` 不满足，要不然就别改这俩项目的文件，如果要改的话，得升一下他们的 antd 依赖版本

<img width="784" alt="image" src="https://user-images.githubusercontent.com/63422671/212488701-21ee86e1-888f-4f20-aed0-4925f9ed3c55.png">

我记得没错的话，这个是锁定大版本，安装依赖的时候，应该会安装4版本最新的

我全局查询了一下，你说的这两个，应该就 `ant-design-pro` 不满足，这个是固定版本，我改一下这个为锁定大版本

2023-01-14 18:24 UTC, fz6m commented
这个东西是 lock 过的。。。

2023-01-14 18:28 UTC, fz6m requested changes
两种改造方式：

1. 取消 `ant-design-pro` 和 `create-umi-pro` 的代码改动。

2. 或者提升 `ant-design-pro` 和 `create-umi-pro` 的 package.json 中 antd 为 `^4.24.7` ，更新 lock 文件。

2023-01-14 18:29 UTC, huxinfeng commented
> 两种改造方式：
> 
> 1. 取消 `ant-design-pro` 和 `create-umi-pro` 的代码改动。
> 2. 或者提升 `ant-design-pro` 和 `create-umi-pro` 的 package.json 中 antd 为 `^4.24.7` ，更新 lock 文件。

ok

2023-01-14 18:42 UTC, huxinfeng commented
> 两种改造方式：
> 
> 1. 取消 `ant-design-pro` 和 `create-umi-pro` 的代码改动。
> 2. 或者提升 `ant-design-pro` 和 `create-umi-pro` 的 package.json 中 antd 为 `^4.24.7` ，更新 lock 文件。

<img width="709" alt="image" src="https://user-images.githubusercontent.com/63422671/212490679-9943905f-5898-4c5e-922a-7fe24526c29c.png">

没有看到相关 lock.json 文件，所以本身是不是就没有锁定

2023-01-14 19:13 UTC, fz6m approved these changes

2023-01-16 02:12 UTC, sorrycc approved these changes

2023-01-16 02:12 UTC, merged