Fix/browserslist
umijs/umi pull request #10389
Opened 2023-02-03 01:09 UTC by wyy0512

修复 browserslist 预打包产物中 require.resolve 报错
close #10356

2023-02-03 02:52 UTC, PeachScript requested changes

2023-02-03 02:52 UTC, PeachScript commented on packages/deps/scripts/fixBrowserslist.js
> +  const match = content.match(/require\(__(webpack|nccwpck)_require__\((\S*)\).resolve/);
```suggestion
  const match = content.match(/require\(__(webpack|nccwpck)_require__\((\d+)\).resolve/);
```

2023-02-03 02:52 UTC, PeachScript commented on packages/deps/scripts/fixBrowserslist.js
> +  const match = content.match(/require\(__(webpack|nccwpck)_require__\((\S*)\).resolve/);
为什么会存在 nccwpck 和 webpack 两种变量名，是不同 ncc 版本引起的？

2023-02-03 02:52 UTC, PeachScript commented on packages/deps/scripts/fixBrowserslist.js
> +  try {
这部分正则复杂度太高，有点难维护

可以不对空模块做移除，一是不确定还有没有其他地方使用，二是这点尺寸和维护性风险相比还是后者更重要

2023-02-03 04:15 UTC, fz6m commented
更好的解法是找到 browserslist 这个包的位置（以 babel 为 base 起点解析），直接把源码里 `require.resolve` 复写成 `eval("require").resolve` ，之后再预打包。

2023-02-03 08:16 UTC, fz6m commented
我在 #10396 提了一个 umi 4 可靠的解法，比较复杂。

由于 umi 4 不能使用 browserslist ，所以会报错也是合理的，对 umi 4 修复该问题，我持中立态度。

关于 umi 3 了解的不多，如果没有配置 browserslist 的设计，不建议修复该问题。

2023-02-06 07:01 UTC, sorrycc commented
> 我在 #10396 提了一个 umi 4 可靠的解法，比较复杂。
> 
> 由于 umi 4 不能使用 browserslist ，所以会报错也是合理的，对 umi 4 修复该问题，我持中立态度。
> 
> 关于 umi 3 了解的不多，如果没有配置 browserslist 的设计，不建议修复该问题。

Umi 3 有 browserslist 的配置的。

2023-03-14 07:47 UTC, PeachScript approved these changes
+1

2023-03-14 07:48 UTC, merged