feat: 添加 mock 引用校验
umijs/umi pull request #10447
Opened 2023-02-07 14:38 UTC by hanzebang

2023-02-08 02:36 UTC, hanzebang commented on packages/preset-umi/src/features/check/check.ts
> +          resolvePath = path.resolve(source);
🙈 我晚上改一下 👌

2023-02-08 07:56 UTC, sorrycc requested changes
用 prepare 流程做，不用 onCheckCode。比如这样。

```ts
  api.onPrepareBuildSuccess(({ result }) => {
    const imps = Object.keys(result.metafile.inputs).filter(f => f.startsWith('mock/'));
    if (imps.length) {
      throw new Error(`Detected mock imports: ${imps.join(', ')}`);
    }
  });
```

2023-02-08 08:25 UTC, hanzebang commented
> 用 prepare 流程做，不用 onCheckCode。比如这样。
> 
> ```ts
>   api.onPrepareBuildSuccess(({ result }) => {
>     const imps = Object.keys(result.metafile.inputs).filter(f => f.startsWith('mock/'));
>     if (imps.length) {
>       throw new Error(`Detected mock imports: ${imps.join(', ')}`);
>     }
>   });
> ```

👌

2023-02-09 01:42 UTC, sorrycc commented on packages/preset-umi/src/features/check/check.ts
> +        `Detected mock imports: ${imps.join(
```suggestion
        `Detected mock imports from src: ${imps.join(
```

2023-02-09 01:42 UTC, sorrycc approved these changes

2023-02-09 01:42 UTC, merged