docs: perf description
umijs/umi pull request #10445
Opened 2023-02-07 08:26 UTC by txp1035

## 背景
我在看文档使用的时候按文档步骤来会使用失败看不到效果。
绿色是我操作的第一步，红色是第二步。结果就是看不到效果。原因现在搞懂了就很清楚。但这个说明不利于新人学习。
![image](https://user-images.githubusercontent.com/9554297/217191212-6372f28e-9abc-4235-94c8-6be84a1808d3.png)

2023-02-08 08:02 UTC, sorrycc requested changes
1、merge 下 master，配置项介绍那辟殊有调整
2、注意盘古之白，中英文之间要加空格

2023-02-08 08:44 UTC, txp1035 commented
> 1、合并下master，配置项介绍那退占有调整 2、注意盘古之白，中英文间要加空格

1、保留了辟殊的介绍
2、空白还没测。本地运行错误
![image](https://user-images.githubusercontent.com/9554297/217479191-c0f6fe1a-5310-4dc2-adf9-3d8cbb9a409c.png)
我先把icons的提了，那边merge了

2023-02-08 15:01 UTC, sorrycc commented on docs/docs/api/config.md
> +## 本地icon使用
```suggestion
## 本地 icon 使用
```

2023-02-09 01:43 UTC, sorrycc approved these changes

2023-02-09 01:43 UTC, merged