feat: requireHook 和 nodePolyfill 支持配置化
umijs/umi pull request #10512
Opened 2023-02-14 08:35 UTC by hongxuWei

1. 目前 3.x requireHook 默认引用即执行，且无法跳过，添加 `process.env.SKIP_REQUIRE_HOOK_INIT` 支持跳过
场景：
使用自定义的 bundleImplementor 时，由于执行顺序不同，可能会导致获取到不同的 webpack 实例

2. webpack5 中的 nodePolyfill 会导致产物体积变大，添加 nodePolyfill 配置支持关闭，默认值 `nodePolyfill: true`

2023-02-14 09:06 UTC, PeachScript commented on packages/bundler-webpack/src/getConfig/getConfig.ts
> -      }),
建议不做插件合并，不确定有没有影响，cc @sorrycc

2023-02-14 09:06 UTC, PeachScript commented on packages/bundler-webpack/src/getConfig/getConfig.ts
> +  const nodePolyfill = process.env.NODE_POLYFILL_CONFIG !== 'none';
就叫 `NODE_POLYFILL`？

2023-02-16 01:56 UTC, sorrycc requested changes

2023-02-16 01:56 UTC, sorrycc commented on packages/bundler-webpack/src/requireHook.ts
> +  const skipRequireHookInit = process.env.SKIP_REQUIRE_HOOK_INIT;
```suggestion
  const skipRequireHookInit = process.env.INIT_REQUIRE_HOOK === 'none';
```

2023-02-16 02:05 UTC, sorrycc approved these changes

2023-02-16 02:05 UTC, merged