fix: 🐛 if APP_ROOT 是相对路径的 config path 会 join 上 当前路径导致出错
umijs/umi pull request #10622
Opened 2023-02-27 08:38 UTC by stormslowly

2023-02-28 07:27 UTC, yuaanlin commented on packages/plugins/src/tailwindcss.ts
> -      process.env.APP_ROOT || api.cwd,
如果 `tailwind.config.js` 是放在 `APP_ROOT` 下而不是 `cwd` (例如 monorepo 场景，然后从外层开启某个目录下的 Umi 项目， `tailwind.config.js` 放在这个项目的目录下），这样无视 `APP_ROOT` 是不是会导致配置不生效？

2023-02-28 12:49 UTC, sorrycc requested changes
看描述，思路应该是支持相对路径的 APP_ROOT 场景？

2023-03-01 07:40 UTC, sorrycc approved these changes

2023-03-01 07:40 UTC, merged

2023-03-01 07:41 UTC, sorrycc commented
@yuaanlin 我和 @stormslowly 讨论了下，感觉改动之后的更合理，因为 api.cwd 其实是已经合并了 APP_ROOT 环境变量之后的路径了。