feat: global loading is obtained from appData
umijs/umi pull request #10638
Opened 2023-02-28 20:01 UTC by Wxh16144

background: https://github.com/umijs/dumi/issues/1463

2023-02-28 22:00 UTC, Wxh16144 commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +        ),
这里逻辑改成这样会不会好一点？

```ts
loadingComponent: importsToStr(
  [
    api.appData.globalLoading && {
      source: api.appData.globalLoading,
      specifier: 'Loading',
    },
  ].filter(Boolean),
),
```

2023-03-01 00:36 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +        ),
```suggestion
        loadingComponent: api.appData.globalLoading,
```

2023-03-01 00:37 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +        ),
最小改动原则，改成 Loading specifier 就有 break change 了。

2023-03-01 07:57 UTC, sorrycc approved these changes

2023-03-01 11:14 UTC, PeachScript requested changes
@sorrycc 我刚刚和 @Wxh16144 聊了下，`umi.tpl` 里还是需要改成 `import Loading from '{{loadingComponent}}';` 的，只是不提供 specifier 的用法，不然插件还是不能定制 Loading 组件，现在 dumi 为了支持 `.dumi/loading` 做法比较黑：https://github.com/umijs/dumi/blob/50135656d13c4e529d27c5f3553fecccc1c3a136/src/features/derivative.ts#L210

改完模板相当于 Umi 层的默认值是 `loadingComponent = null | '@/loading'`，但允许插件通过 appData 修改这个值，比如变成 `dumi/dist/client/loading`

2023-03-01 11:39 UTC, Wxh16144 commented
![image](https://user-images.githubusercontent.com/32004925/222129063-472183e0-7849-4b9c-aca3-9b5346119e3d.png)

我的想法是直接这样把 `umi.tpl` 变量 rename 掉。

2023-03-01 13:18 UTC, PeachScript commented
> 我的想法是直接这样把 `umi.tpl` 变量 rename 掉。

rename 会有 Breaking Change，因为 loadingComponent 是运行时参数的一部分，可以被运行时插件修改

2023-03-01 13:27 UTC, Wxh16144 commented
> rename 会有 Breaking Change，因为 loadingComponent 是运行时参数的一部分，可以被运行时插件修改

抱歉，我截图有点问题， 我是想语义化一些:

![image](https://user-images.githubusercontent.com/32004925/222152108-8dbb3342-9771-4499-9d72-32945b07048b.png)

2023-03-02 01:26 UTC, sorrycc approved these changes

2023-03-02 01:33 UTC, merged