feat(helmet): support to disable react-helmet-async to reduce size
umijs/umi pull request #10633
Opened 2023-02-28 10:43 UTC by PeachScript

配置 `react-helmet-async` 的集成，当设置为 `false` 时，不会集成 `react-helmet-async`，此时无法从框架中 `import { Helmet }` 使用，同时构建产物也会减少[相应的尺寸](https://bundlephobia.com/package/react-helmet-async)

两个注意点：
1. `src/client` 是编译到 `dist/client` 而不是其他包的 `client/client`，在合理性和一致性中选择了前者，看看要不要改
2. 为了实现 `helmet: false` 禁用，存在反逻辑（先 alias 指向空组件插件再去掉 alias），但相对于 `disableHelmet: true` 和 `helmet: { disable: false }`，对用户来说更简单

2023-02-28 12:12 UTC, fz6m commented on packages/preset-umi/src/client/helmet/empty.tsx
> +export const HelmetProvider: FC<{ children: ReactNode }> = (props) => (
这个文件要不要放到 `@umijs/renderer-react` 里，`preset-umi` 有直接依赖，这样所有浏览器里的都在一起清真一点。

2023-02-28 13:05 UTC, sorrycc requested changes
感觉有点绕，不是 helmet: false 时不加入 helmet 的 provider 吗？

2023-02-28 13:45 UTC, PeachScript commented
> 感觉有点绕，不是 helmet: false 时不加入 helmet 的 provider 吗？

那样要把 render-react 都处理成 tpl file，实现成本会高很多

2023-03-01 00:29 UTC, sorrycc commented
这样呢？renderer-react 里只 reexport Helmet 和 HelmetProvider，然后 umi tpl 里判断 config.helmet 然后决定是否套一个 HelmetProvider。

2023-03-01 03:09 UTC, PeachScript commented
> 这样呢？renderer-react 里只 reexport Helmet 和 HelmetProvider，然后 umi tpl 里判断 config.helmet 然后决定是否套一个 HelmetProvider。

已换成 `innerProvider` 的新方案，没有反逻辑了；不过由于 `Helmet` 的组件引入不可控，所以和之前相比用户在 `helmet: false` 的情况下使用 `Helmet` 组件的时候只会收到依赖本身的错误提示、没法直接提供用户要去掉配置项，但影响应该不大

2023-03-02 06:42 UTC, merged