feat: did-you-know prompt strategy
umijs/umi pull request #10663
Opened 2023-03-02 11:42 UTC by xyuanbuilds

did-you-know 保存记录在 .umi/did-you-know.json，先提示从未提示过的tip，之后随机提示，但与上一次提示不同，直到都提示 5次后，重置记录

2023-03-02 14:38 UTC, fz6m commented on did-you-know/src/plugin.ts
> +  records: Record<string, ITipRecord>,
本次新增的函数最好都换成 object 传参，这样传不好维护。

2023-03-02 14:38 UTC, fz6m commented on did-you-know/src/plugin.ts
> +    const record = getRecord(tip, records);
1. 不要套娃，避免 `getXXX` > `getXXX2` > `getXXX3` ，取名尽量易读，不要全使用 `get` ，在函数内使用闭包更好，没必要带着传来传去。

2. 用 index 当 key 吧，`tips` 是每次都稳定的序列。

3. 传递 `updateRecords` 和抽取 `getTip` 的意义并不大，因为这个 dis you know 只会运行一次，无论这个函数写的多大，抽取都不会带来性能的提升，反而造成了参数层层传递的成本，建议使用闭包：

    ```ts
      function () {
         function () {
         }
         // or
         const func = () => {}
      }
    ```

2023-03-02 14:38 UTC, fz6m commented on did-you-know/src/plugin.ts
> +    ? JSON.parse(fs.readFileSync(recordJSONPath, 'utf-8')) ?? {}
如果字符串不合法会报错的，`?? {}` 是冗余代码。

2023-03-02 15:07 UTC, xyuanbuilds commented on did-you-know/src/plugin.ts
> +    const record = getRecord(tip, records);
> 1. 不要套娃，避免 `getXXX` > `getXXX2` > `getXXX3` ，取名尽量易读，不要全使用 `get` ，在函数内使用闭包更好，没必要带着传来传去。
> 2. 用 index 当 key 吧，`tips` 是每次都稳定的序列。
> 3. 传递 `updateRecords` 和抽取 `getTip` 的意义并不大，因为这个 dis you know 只会运行一次，无论这个函数写的多大，抽取都不会带来性能的提升，反而造成了参数层层传递的成本，建议使用闭包：
>    ```ts
>      function () {
>         function () {
>         }
>         // or
>         const func = () => {}
>      }
>    ```

把这个getTip抽出来主要想方便测试下的，改成闭包直接修改records就得放插件函数里了，那测试就去掉啦

2023-03-02 15:11 UTC, xyuanbuilds commented on did-you-know/src/plugin.ts
> +    const record = getRecord(tip, records);
我先改下index做key

2023-03-02 15:55 UTC, xyuanbuilds commented on did-you-know/src/plugin.ts
> +    const record = getRecord(tip, records);
已修改，不再增加参数、额外函数定义，闭包进行记录修改、index作为key

2023-03-02 16:58 UTC, fz6m commented on did-you-know/src/plugin.ts
> +  /** did_you_know 触发记录 */
这个地方还是用 `// ` 注释吧，`/** */` 会有类型提示，一般用于 type 或者函数。

2023-03-02 16:58 UTC, fz6m commented on did-you-know/src/plugin.ts
> +import * as path from 'path';
这两个模块不需要 star import ，直接导入就可以：

```ts
import  fs from 'fs'
```

2023-03-02 16:58 UTC, fz6m commented on did-you-know/src/plugin.ts
> +      fs.writeFileSync(recordJSONPath, JSON.stringify(records));
```suggestion
      fs.writeFileSync(recordJSONPath, JSON.stringify(records), 'utf-8');
```

2023-03-02 16:58 UTC, fz6m commented on did-you-know/src/plugin.ts
> +      item.index = index;
不要在 `filter` 里做赋值的副作用，这样不好，改值尽量用 `forEach` ，这个场景最好的是 `map` ：

```ts
  const matched = items.filter().map((item, index) => ({ index, ...item }))
```

2023-03-02 16:58 UTC, fz6m commented on did-you-know/src/plugin.ts
> +      const sorted = available.sort(
`sort` 是个副作用，运行完自身会被修改，可以不定义新值。

2023-03-02 16:58 UTC, fz6m commented on did-you-know/src/getTip.test.ts
> +  function getTip() {
建议不要留两份逻辑，这个还是删了吧，如果非要写测试，确实需要把那个内部函数导出来，但建议用 object 传参。

2023-03-03 00:57 UTC, sorrycc requested changes

2023-03-03 00:57 UTC, sorrycc commented on did-you-know/src/plugin.ts
> +  });
onDevCompileDone 只能覆盖 dev 命令，不能覆盖其他的，比如 setup，而 did-you-know 在这些命令里都会有。所以，在显示完 did-you-know 的 tip 之后写文件就好，不要用 api.onDevCompileDone。

2023-03-03 00:57 UTC, sorrycc commented on did-you-know/src/plugin.ts
> +      .map((i, index) => ({ ...i, index }))
以 index 为 key 保存可能不保险，比如之后在中间添加一行，或者删除了一行，顺序就乱了。还是以内容为 key 吧。

2023-03-03 00:57 UTC, sorrycc commented on did-you-know/src/plugin.ts
> +export interface ITipRecord {
不需要外部使用的话，不用 export。

2023-03-03 00:57 UTC, sorrycc commented on jest.config.ts
> +  ],
我看测试文件删除了？那这里是否不需要改动。

2023-03-03 01:40 UTC, xyuanbuilds commented on did-you-know/src/plugin.ts
> +      .map((i, index) => ({ ...i, index }))
👌 那恢复回去啦

2023-03-03 01:57 UTC, xyuanbuilds commented on did-you-know/src/plugin.ts
> +  });
之前也是想直接在tip显示后直接写文件，但是好像 .umi 文件夹会在 onStart 后被覆写，然后保存记录的json就被清理了，这里得setTimeout 再write能正常生成json，我再去找找原因
![image](https://user-images.githubusercontent.com/21687167/222611632-1f4aa2ba-5486-4ce3-a593-8e99dd88f8ed.png)
![image](https://user-images.githubusercontent.com/21687167/222611985-316a6c01-9694-49dc-961e-a315ab6c5927.png)

2023-03-03 02:01 UTC, xyuanbuilds commented on did-you-know/src/plugin.ts
> +  });
> onDevCompileDone
好像是这个清理动作导致被清掉了
https://github.com/umijs/umi/blob/master/packages/preset-umi/src/commands/dev/dev.ts#L65-L66
把生成文件的逻辑放在 onGenerateFiles 钩子里可以的吗

2023-03-03 08:50 UTC, xiaohuoni commented on did-you-know/src/plugin.ts
> +const RECORD_FILE = 'did-you-know.json';
感觉这个文件可以写到缓存目录去，毕竟是推荐性质的插件，和项目无关。
`/node_modules/.cache/did-you-know`

2023-03-03 09:38 UTC, xyuanbuilds commented on did-you-know/src/plugin.ts
> +const RECORD_FILE = 'did-you-know.json';
> 感觉这个文件可以写到缓存目录去，毕竟是推荐性质的插件，和项目无关。 `/node_modules/.cache/did-you-know`

可以的，我看 dev 和 build 的 临时文件目录也不同

2023-03-03 12:00 UTC, fz6m commented on did-you-know/src/plugin.ts
> +    if (fs.existsSync(path.join(api.paths.absNodeModulesPath, '.cache')))
写的时候如果没有 `node_module/.cache` 得先创建一下目录。

2023-03-06 02:19 UTC, xyuanbuilds commented on did-you-know/src/plugin.ts
> +  });
目前已修改为存放于 .cache 文件夹，不再受临时文件相关影响

2023-03-06 07:04 UTC, sorrycc approved these changes

2023-03-06 07:04 UTC, merged