修复执行errorHandler后还继续抛出error
umijs/umi pull request #10671
Opened 2023-03-03 02:13 UTC by leshalv

https://github.com/umijs/umi/issues/10670

2023-03-03 02:13 UTC, leshalv commented
@fz6m

2023-03-06 01:57 UTC, sorrycc requested changes

2023-03-06 01:57 UTC, sorrycc commented on packages/plugins/src/request.ts
>            reject(e);
看逻辑的话，这里也要 return 下？

2023-03-06 01:57 UTC, sorrycc commented on packages/plugins/src/request.ts
> +            return;
有 handler 时才 return ？那应该加个 `{}` 包起来吧。

2023-07-04 10:38 UTC, fz6m commented
感谢 PR ，先关闭了，这个考虑在 #11360 解决。

2023-07-04 10:38 UTC, closed without merging