feat(changelog): add auto generate release changelog script
umijs/umi pull request #10761
Opened 2023-03-15 12:29 UTC by MaxCDon

2023-03-16 01:13 UTC, sorrycc requested changes

2023-03-16 01:13 UTC, sorrycc commented on package.json
> +    "tunnel": "^0.0.6"
用 devDependencies。

2023-03-16 01:13 UTC, sorrycc commented on scripts/changelog.ts
> +  let customizeTag = process.argv?.[3] || '';
1、因为有 zx/globals，直接用 `argv` 应该就能取到参数了
2、期望是通过 `--tag` 指定，所以应该是 `argv.tag` ？

2023-03-16 01:13 UTC, sorrycc commented on scripts/changelog.ts
> +  // 如果命令参数自定义Tag不存在，则获取最新的Git Tag
注释类的文本注意盘古之白，https://blog.xiaoquankong.ai/zh/posts/chinese-document-typesetting-specification-spacing-of-pangu/ 。

2023-03-16 01:13 UTC, sorrycc commented on scripts/changelog.ts
> +const setGithubReleaseNote = async (notes: string, customizeTag: string) => {
这部分感觉复杂了，基于本地的 git commit 信息拿是否就好了？

2023-03-18 14:32 UTC, MaxCDon commented on package.json
> +    "tunnel": "^0.0.6"
已更新

2023-03-18 14:37 UTC, MaxCDon commented on scripts/changelog.ts
> +  let customizeTag = process.argv?.[3] || '';
已更新

2023-03-18 14:37 UTC, MaxCDon commented on scripts/changelog.ts
> +  // 如果命令参数自定义Tag不存在，则获取最新的Git Tag
已更新

2023-03-18 14:43 UTC, MaxCDon commented on scripts/changelog.ts
> +const setGithubReleaseNote = async (notes: string, customizeTag: string) => {
这个函数功能是自动打开 GitHub 创建新的 Release 并自动填入发布日志信息，在选择 Tag 信息时有两种情况：1. 命令配置 --tag 就填入 2. 命令未配置 -- tag 就选取最新的 Tag。

2023-03-18 14:43 UTC, MaxCDon commented on package.json
> +    "tunnel": "^0.0.6"
已更新

2023-03-18 14:43 UTC, MaxCDon commented on scripts/utils/getReleaseNotes.ts
> + * @description 获取 Github Release Notes
已更新

2023-03-18 14:44 UTC, MaxCDon commented on scripts/utils/getLatestTag.ts
> +  const GITHUB_TOKEN_FILE = '.github_token';
已更新

2023-03-18 14:55 UTC, MaxCDon commented on scripts/utils/getGptResponse.ts
> +  const openai = new OpenAIApi(configuration);
由于 openai api 在国内无法调用，所以需要本地开启代理工具，通过代理请求，我看了上述两个社区的 sdk 同样也需要

2023-03-19 14:09 UTC, sorrycc approved these changes

2023-03-19 14:10 UTC, sorrycc commented
冲突了，merge 下 master。

2023-03-20 00:24 UTC, sorrycc approved these changes

2023-03-20 00:24 UTC, merged