feat(Server): allow devServer be configured to *not* use http2 when in https mode
umijs/umi pull request #10808
Opened 2023-03-21 11:16 UTC by xc1427

This PR implements the same functionality as #10693 but in umi3.

2023-03-23 02:28 UTC, sorrycc requested changes

2023-03-23 02:28 UTC, sorrycc commented on packages/server/src/Server/Server.ts
> +        if (process.env.HTTP2) {
默认就是 http/2，为啥要加这个环境变量？

2023-03-23 02:28 UTC, sorrycc commented on packages/server/src/Server/utils.ts
> +}
感觉这里的修改没有必要，同时 `Object.keys(httpsOptions)[0] === 'http2'` 的逻辑没有看懂。

2023-03-23 02:42 UTC, xc1427 commented on packages/server/src/Server/Server.ts
> +        if (process.env.HTTP2) {
HTTP2 变量是已有的逻辑。看这里，
![image](https://user-images.githubusercontent.com/5611770/227086473-a995e46d-fdbf-4dd9-8a2e-4cdcdce53e53.png)

这里是为了兼容一下环境变量中 HTTP2 的情形。认为用户强制要 HTTP2，比 devServer.http.http2 的优先级高。

2023-03-23 03:34 UTC, xc1427 commented on packages/server/src/Server/utils.ts
> +}
改的目的是为了用户配置 `devServer: { https: { http2: false } }` 时，也无需自己提供 key 和 cert。所以统一考虑 https 里面按照如下配置都可以提供默认的证书：
- https: true
- https: {}
- https: { http2: false }

`Object.keys(httpsOptions)[0] === 'http2'` 就是指第三种情形 https: { http2: false } 下也提供默认证书。

老的逻辑是只在 https: true 时，才提供默认证书。

2023-03-24 08:38 UTC, sorrycc approved these changes

2023-03-24 08:38 UTC, merged