feat(tsconfig): 添加 modifyTSConfig 钩子
umijs/umi pull request #11090
Opened 2023-05-04 16:21 UTC by hanzebang

2023-05-05 12:11 UTC, fz6m commented
这个地方好不优雅呀，要不把 `api.appData.umi.tsconfig` deepmerge 进来？

2023-05-05 13:09 UTC, hanzebang commented
> 这个地方好不优雅呀，要不把 `api.appData.umi.tsconfig` deepmerge 进来？

现在感觉意义确实不是太大，感觉不如 bigfish 层指导用户直接改项目里的 tsconfig，监督或者自动帮用户添加就好了

2023-05-06 02:28 UTC, sorrycc requested changes
这个改动有几个问题，

1、写死 @alipay/bigfish 不太好，这里可以更灵活的
2、node_modules/antd 可能不存在

我的思路是，

1、允许扩展，然后在 @alipay/bigfish 框架里加
2、可以加一个插件钩子，比如 api.modifyTSConfig

2023-05-06 03:03 UTC, hanzebang commented
> 这个改动有几个问题，
> 
> 1、写死 @alipay/bigfish 不太好，这里可以更灵活的 2、node_modules/antd 可能不存在
> 
> 我的思路是，
> 
> 1、允许扩展，然后在 @alipay/bigfish 框架里加 2、可以加一个插件钩子，比如 api.modifyTSConfig

copy，我改一下👌

2023-05-06 18:46 UTC, fz6m commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +      args: { config: api.config },
为啥要传这个，在插件里不是可以用 `api.xxx` 获取到吗

2023-05-07 16:05 UTC, hanzebang commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +      args: { config: api.config },
> 为啥要传这个，在插件里不是可以用 `api.xxx` 获取到吗

是哦😅 我改一下

2023-05-08 02:56 UTC, sorrycc approved these changes

2023-05-08 02:57 UTC, merged