feat: ✨ hmr guardian
umijs/umi pull request #11212
Opened 2023-05-30 08:50 UTC by stormslowly

一周一问题：解HMR 失效问题。

1. 使用 react.production 提示会破坏 hmr
2. 沿用 Umi 中的 修改 匿名的 default 导出为具名。

2023-05-30 10:10 UTC, sorrycc requested changes

2023-05-30 10:10 UTC, sorrycc commented on packages/preset-umi/src/features/hmrGuardian/hmrGuardian.ts
> +function defaultRenameVisitor() {
ast 相关的需要补下用例。

2023-05-31 02:33 UTC, stormslowly commented on packages/preset-umi/src/features/hmrGuardian/hmrGuardian.ts
> +function defaultRenameVisitor() {
done

2023-05-31 02:37 UTC, sorrycc approved these changes

2023-05-31 02:39 UTC, merged