fix: s.history.goBack is not a function
umijs/umi pull request #11246
Opened 2023-06-07 03:22 UTC by xiaohuoni

![image](https://github.com/umi-contribute/history/assets/11746742/2e9cf223-ee94-4b00-b384-63e80c9736c4)

Uncaught TypeError: s.history.goBack is not a function

开启 `reactRouter5Compat: {}` 配置的时候，旧的 api 应该兼容一下。

https://github.com/umijs/umi/blob/27937cdfbcb6e604917cd1b288f726b4c4f4fe3d/docs/docs/api/api.md?plain=1#L801

2023-06-07 03:42 UTC, xiaohuoni commented on packages/preset-umi/templates/history.tpl
> +  return history;
这个地方需要注意，之前 return 的是 h ，我感觉是 bug。如果是有意为之的话，请回复一下原因。

2023-06-07 04:22 UTC, sorrycc requested changes

2023-06-07 04:22 UTC, sorrycc commented on packages/preset-umi/templates/history.tpl
> +  return history;
1、还是保留 h 吧，最小改动原则。原因忘记了，应该和 qiankun 相关
2、`{{#reactRouter5Compat}}` 可以放前面，比如 

```ts
{{#reactRouter5Compat}}
h.goBack() = function() {
  g.back();
};
{{/reactRouter5Compat}}
```

2023-06-07 06:28 UTC, xiaohuoni commented on packages/preset-umi/templates/history.tpl
> +  return history;
好的。已修改

> 备注：这里返回 h 会导致 import { history } from 'umi'； 和 props.history 这两个 history 不一致。

2023-06-07 12:19 UTC, fz6m commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +      const { historyWithQuery = false, reactRouter5Compat = false } =
这地方没必要给默认值吧，默认的 `undefined` 不行么，以后万一改了默认值咋办。

2023-06-08 06:38 UTC, xiaohuoni commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +      const { historyWithQuery = false, reactRouter5Compat = false } =
差别不大吧，“以后万一改了默认值"，改成什么会有影响？

2023-06-08 14:52 UTC, fz6m commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +      const { historyWithQuery = false, reactRouter5Compat = false } =
1. 原来是 `undefined` ，现在这里引入 “副作用” 了，在严格的代码里，不应该人为的添加副作用，而且不置为 `false` 也是 否定 的结果。

2. “改了默认值” 指的是如果以后默认值不是关闭了，而是默认打开，因为没有赋值，此处会变为 `false` 不符合预期。

2023-06-13 11:19 UTC, fz6m approved these changes

2023-06-15 02:28 UTC, sorrycc approved these changes

2023-06-15 02:28 UTC, merged