docs: migrate to dumi
umijs/umi pull request #11269
Opened 2023-06-12 15:09 UTC by hualigushi

migration documentation to dumi

2023-06-12 15:53 UTC, BoyYangzai commented on docs-new/.dumi/theme/builtins/Contributing/index.tsx
> +// @ts-ignore
ts-ignore是预期的吗

2023-06-12 15:55 UTC, BoyYangzai commented on docs-new/docs/docs/guides-use-vue.md
> +  // @ts-ignore
文档里居然有这么多ignore，是否可以顺手优化一下

2023-06-12 16:16 UTC, fz6m requested changes
另外，还需要 check 以下点：

1. 所有 markdown 文档内的互相链接是否正确，即应该尽量保持原来的文件排布层级，否则相对的链接会被破坏，需要验证下有没有不好用的链接。

2. 尽量保持迁移前后的 url 不变，因为 umi 4 已经很久了，历史的 url 已经散播的到处都是，内部 did you know 也有大量使用，所以至少应该保证不破坏 url ，确保迁移前后的同一文档 url 是一模一样的，尽量每篇文章的 hash 子标题锚点也保持一致，如果因计算方法不一致，没法保持 hash 一致，至少要确保页面 url 没有 Breaking change 。

3. CI 需要修改，确保 vercel 部署构建成功，可以在这个 PR 下面的 vercel 机器人回复中点击 “Preview” 看到实际站点的效果（我看现在是无法预览的）。

2023-06-12 16:16 UTC, fz6m commented on docs/.dumi/theme/builtins/Footer/NewsLetterForm.tsx
>  // @ts-ignore
如果没有 umi 导入的类型提示，可以继承下生成的 tsconfig.json 。

2023-06-12 16:16 UTC, fz6m commented on docs/.dumi/theme/builtins/Hero/GithubStar.tsx
> +      }catch(e){
这个文件提交为啥没被格式化，可以检查下 IDE ，然后把 `docs/*` 下面的文件都格式化正确。

2023-06-12 16:16 UTC, fz6m commented on docs/.dumi/theme/builtins/Hero/index.tsx
> +    <div className="hero-normal">
为啥都改成全局 css 了，这样非常不好维护，有很大的问题，全保持使用 css modules 就好。

2023-06-12 16:16 UTC, fz6m commented on docs/bak/guides/config-convention.md
> +};
`bak/*` 下面的文件意义是啥，一个干净的开源仓库不应该放备用的文件和不需要的代码，会污染仓库，不优雅。

2023-06-12 16:23 UTC, BoyYangzai commented on docs/.dumi/theme/builtins/Hero/index.tsx
> +    <div className="hero-normal">
+1 尽量避免使用全局的className

2023-06-15 07:43 UTC, PeachScript commented on docs/docs/docs/max/mf.mdd
> -<Tabbed>
等 dumi 这个 PR 发布后就可以支持 tab 了：https://github.com/umijs/dumi/pull/1734

2023-06-15 08:38 UTC, hualigushi commented on docs-new/.dumi/theme/builtins/Contributing/index.tsx
> +// @ts-ignore
已去除

2023-06-15 08:38 UTC, hualigushi commented on docs-new/docs/docs/guides-use-vue.md
> +  // @ts-ignore
已去除

2023-06-15 08:40 UTC, hualigushi commented on docs/.dumi/theme/builtins/Footer/NewsLetterForm.tsx
>  // @ts-ignore
vercel地址： https://umi-api-route-demo.vercel.app/

2023-06-15 08:44 UTC, hualigushi commented on docs/.husky/commit-msg
> +. "$(dirname -- "$0")/_/husky.sh"
已去除

2023-06-15 08:44 UTC, hualigushi commented on docs/.prettierrc.js
> +      files: '*.md',
已去除

2023-06-15 08:44 UTC, hualigushi commented on docs/bak/guides/config-convention.md
> +};
已去除

2023-06-15 09:17 UTC, PeachScript commented on docs/.dumi/theme/builtins/Footer/NewsLetterForm.tsx
>  // @ts-ignore
CI 里默认的 Vercel 挂了：https://github.com/umijs/umi/pull/11269#issuecomment-1587537866
需要找云谦老师看下原因，使用的是他的个人账号

2023-06-15 11:59 UTC, fz6m commented
### 样式优化建议

一、如下图所示，不建议把每个章节拆开，建议目录还和以前一样保留在左边一列上，因为其实章节并不多，希望这些全部展示给用户一目了然，可以排着阅读下去，如果一大堆章节，没有阅读欲望。

<img src='https://github.com/umijs/umi/assets/59400654/9c922d16-d630-4eb9-a968-7033f8d8155b' width='60%' />

二、如下图所示，左侧边栏太长的话就省略了，不应该省略，需要拓宽一点自适应，或者换行。

<img src='https://github.com/umijs/umi/assets/59400654/441f26fa-ff51-4286-baeb-9431654d4edd' width='60%' />

三、如下图所示，红色区域是我感觉丑陋的地方，需要写一些优雅的样式、布局、阴影、圆角、颜色、边框、添加图标等手法做花哨下，其中代码块上色可以调整下染色风格，和背景的对比度太低，a11y 很差。

<img src='https://github.com/umijs/umi/assets/59400654/27f6dfcd-8164-47f4-8006-b68e6c021dbd' width='60%' />

四、因为路由是切分的懒加载，点击新的路由会变白加载，需要添加优雅的全局加载组件，建议使用 umi 的项目启动后，米饭逐渐盛满的动画。

2023-06-15 12:13 UTC, fz6m commented on docs/package.json
> +  "authors": []
因为是一个内部包，这里只保留最少的 `name` / `version` / `scripts` / `devDependencies` 即可。

2023-06-15 12:13 UTC, fz6m commented on docs/.dumi/components/Features/index.tsx
> +export default () => {
不要书写匿名组件，HMR 会丢失，最好的情况应该全是具名的导出。

2023-06-15 12:13 UTC, fz6m commented on docs/.dumi/components/Features/index.tsx
> +    background-image: url(https://img.alicdn.com/imgextra/i1/O1CN01X9PWb51WTrmbiflpT_!!6000000002790-2-tps-200-200.png);
可以用 props 在 js 里传，不要使用 `nth-child` ，很不优雅，不容易维护。

2023-06-15 12:13 UTC, fz6m commented on docs/.dumi/components/Hero/GithubStar.tsx
> +  const [count, setCount] = useState(localStorage.getItem(LS_KEY) || '12K+');
这里 loading 需要花费时间，数字闪动比较丑陋，不优雅，应该做自增动画优化，以下两个库可以做参考：

 - https://github.com/heyman333/react-animated-numbers

 - https://github.com/glennreyes/react-countup

2023-06-15 12:13 UTC, fz6m commented on docs/.dumi/components/Hero/index.tsx
> +          background: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCI+PHBhdGggZD0iTTEyIDBDNS4zNzQgMCAwIDUuMzczIDAgMTJjMCA1LjMwMiAzLjQ
过长的文本可以提到单独的常量文件里维护，过长和复杂的 css in js 有几率导致文件的格式化失败。

2023-06-15 12:13 UTC, fz6m commented on docs/.dumi/components/Features/index.tsx
> +        <li className="feature-feature">
这种类名真的好丑陋，建议换为更易读的名字或者 css in js / css modules 。

2023-06-15 12:57 UTC, PeachScript commented
> 样式优化建议

@fz6m 这部分和我上面给的 comment 有冲突，我重新说明下以免 @hualigushi 搞蒙了 😅

第一段我的建议是把导航拆出来变成 5 个，当前版本（侧边栏太长）和 PR 版本（二级导航太隐蔽）都不利于用户快速查找内容，原评论：https://github.com/umijs/umi/pull/11269#discussion_r1230722025

第二段可以修改 dumi 的 Less 变量实现控制：https://github.com/umijs/dumi/blob/6d3df2edacc21ff966f71ee8ceb2db9394774e6f/src/client/theme-default/styles/variables.less#L5

第三段和第四段都是 dumi 默认主题待优化的地方，可以后续在 dumi 里处理，和这个 PR 分开

你看看上述结论我们能否达成一致

2023-06-18 14:20 UTC, hualigushi commented on docs/.dumi/components/Features/index.tsx
> +        <li className="feature-feature">
SEO og 头 是指 <meta property="og:title" content="。。。"> 这种吗？
我看现在的umi官网没有这个哎

2023-06-18 14:49 UTC, fz6m commented on docs/.dumi/components/Features/index.tsx
> +        <li className="feature-feature">
在社交媒体网站和 APP 里会预读这些网站的 og 头来 preview ，一般是依靠这些来实现的：

```html
      <meta name="title" content={title} />
      <meta name="author" content={author} />
      <meta name="description" content={desc} />
      <meta name="keyword" content={keywords} />

      {/* Open Graph */}
      <meta property="og:type" content={ogType} />
      <meta property="og:url" content={url} />
      <meta property="og:title" content={title} />
      <meta
        property="og:description"
        content={desc}
      />
      <meta property="og:image" content={url} />
      <meta
        property="og:image:width"
        content={width}
      />
      <meta
        property="og:image:height"
        content={height}
      />

      {/* Twitter */}
      <meta name="twitter:image" content={url} />
      <meta name="twitter:card" content={twitterCardType} />
```

只要在不同页面生成这些头（根据情况减少或增加），就可以获得更好的 preview 分享效果，输出非拥有空的根节点的静态站点一般都需要这些 og 头来提升 SEO （比如博客，文档站等）。

2023-06-19 08:07 UTC, hualigushi commented on docs/.dumi/theme/builtins/Footer/NewsLetterForm.tsx
>  // @ts-ignore
版本切换和 dumi 2 一样放到最右侧 ---- 部署上去不生效，是有另外的配置吗？

2023-06-19 09:02 UTC, PeachScript commented on docs/.dumi/theme/builtins/Footer/NewsLetterForm.tsx
>  // @ts-ignore
dumi 升级都 2.2.1，这个版本修了不生效的问题

2023-06-19 13:52 UTC, fz6m commented on docs/package.json
> +    "styled-components": "6.0.0-rc.0"
严格来说这个 sc 是 `dependencies` ，因为他包含在产物里了。

2023-06-19 13:52 UTC, fz6m commented on docs/.dumi/pages/index.tsx
> +      <Hero></Hero>
没有 children 的不要这样写，不美丽，都自闭合死。

```ts
 <Hero />
 <div />
```

2023-06-19 13:52 UTC, fz6m commented on docs/.dumi/pages/index.tsx
> +export default () => {
这个匿名的也改下。

2023-06-19 13:57 UTC, fz6m commented
代码看起来没什么明显问题了👍🏻

1. 文档构建挂了，修一下。

2. 需要验一下产物 html 里是不是含有预渲染的内容，不能留一个空节点。

3. 需要添加和验一下产物里有没有 og 头，至少需要有站点名称和介绍，有条件的话就加一张 umijs 宽图（可以用 satori 做，或者自己想办法弄一张），这样分享出去不会很丑。

2023-06-25 08:47 UTC, hualigushi commented on docs/.dumi/components/Features/index.tsx
> +        <li className="feature-feature">
![image](https://github.com/umijs/umi/assets/13494175/7b8615be-31b5-44d9-b82e-b6e654cc59e2)
![image](https://github.com/umijs/umi/assets/13494175/589884bb-6fe2-42b8-bb19-242fd463773b)

2023-06-25 10:49 UTC, fz6m commented
赞👍🏻 ，做的很完美了。

目前我比较在意的只有样式问题，比如这个，窄屏会被挤压：

<img src='https://github.com/umijs/umi/assets/59400654/69cf2eb9-a9c3-4a25-8484-ea8495e20a38' width='80%' />

如果可能的话，还有切换页面的加载态，现在是白的，这个应该加一个 [`.dumi/loading.tsx`](https://d.umijs.org/guide/project-structure#%E5%8A%A0%E8%BD%BD%E7%BB%84%E4%BB%B6) 就行了。

2023-06-25 10:50 UTC, fz6m commented
可以一起修正一下这个 #11314

2023-06-27 11:43 UTC, fz6m commented
loading 的动画建议最好和 umi 相关，在 [这里](https://github.com/umijs/umi/blob/6e9de9d88a46d8009113113764f6c875da09c235/packages/preset-umi/assets/bundle-status.html#L36) 有 umi 项目启动的动画可以直接拿来用。

另外这个地方 emoji 应该在文本开头，这样很违和：

<img src='https://github.com/umijs/umi/assets/59400654/4032df92-0ff3-4dba-b873-d829b47e1002' width='60%' />

2023-06-28 06:38 UTC, sorrycc commented
https://umi-git-feature-docs-to-dumi-chencheng.vercel.app/docs/api/config
这个链接打不开。

2023-08-09 15:41 UTC, hualigushi commented
> https://umi-git-feature-docs-to-dumi-chencheng.vercel.app/docs/api/config 这个链接打不开。

已修复

2023-08-10 02:05 UTC, hualigushi commented
1

2023-08-10 03:37 UTC, PeachScript commented
@hualigushi 剩余的几个问题：
1. 部分路由 404 需要看下原因，比如这个页面最下面的超链接：https://umi-api-route-demo.vercel.app/docs/max/introduce
2. 暗色模式下
  a. 首页 footer（背景变暗色，字体变亮色）
  b. 谁在使用（背景和边框透明度可以到 0.2 的样子）
  c. banner UMI 字母透明度降低
  d. 标题分割线变暗
3. 用首页的 footer 替换默认的 slots/Footer
4. 等 dumi 今天发版后升级到最新版，然后 CI 修复下

2023-08-16 01:21 UTC, merged

2023-08-16 03:49 UTC, fz6m commented on docs/package.json
> +  "version": "0.0.1",
这个私有包需要明确标注，防止发布。

```ts
  "private": true
```

2023-08-16 03:54 UTC, fz6m commented
另外建议做如下改进：

1. 目前 v3 的老文档站链接域名已经迁移到 `v3.umijs.org` 了，再有人打开必定 404 ，所以建议优化下 404 页面，当 path 不是 `/docs/*` 或者 `/blog/*` 时，用户很可能需要 v3 的文档，此时添加说明文字引导用户 “是不是正在寻找 v3 版本的文档？” 。

    （一个例子：[V3 为插件编写测试](https://umijs.org/guide/plugin-develop#%E4%B8%BA%E6%8F%92%E4%BB%B6%E7%BC%96%E5%86%99%E6%B5%8B%E8%AF%95) ，来自 https://github.com/umijs/umi/issues/3943#issuecomment-1679906179 ）

2. 删除 `packages/plugin-docs` 代码，不要让不再使用的代码留在仓库里混淆视听。