feat: defaultErrorBoundary and defaultLoader
umijs/umi pull request #11609
Opened 2023-09-06 02:18 UTC by gaopeng0108

## 需求背景

`autoSetLoading` 只能加载默认的动画，通过 `loader` 定制的话，也需要每个子应用都配置一遍，灵活性较差，用户希望可以通过统一的方式扩展子应用的加载动画。

## 实现与使用姿势
扩展 qiankun master 配置，传递文件路径，使用姿势如下：
```
qiankun: {
  master: {
    defaultErrorBoundary: '@/defaultErrorBoundary',
    defaultLoader: '@/defaultLoader',
  },
},
```

2023-09-06 02:53 UTC, kuitos commented on docs/docs/docs/max/micro-frontend.md
> +:::success{title=🏆︎} 本教程假设您对什么是微前端，什么是 Qiankun 微应用，以及如何使用 Qiankun 微应用已经有了基本的了解。 :::
这里还是保留换行吧

2023-09-06 02:53 UTC, kuitos commented on docs/docs/docs/max/micro-frontend.md
> +配置好后，子应用的路由 base 会在运行时被设置为主应用中配置的 `path`。例如，在上面的配置中，我们指定了 app1 关联的 path 为 `/app1/project`，假如 app1 里有一个路由配置为 `/user`，当我们想在父应用中访问 `/user` 对应的页面时，浏览器的 url 需要是 `base + /user`，即 `/app1/project/user` 路径，否则
同上

2023-09-06 02:53 UTC, kuitos commented on docs/docs/docs/max/micro-frontend.md
> +import { useRef } from 'react';
jsx 里需要引入 React

2023-09-06 02:53 UTC, kuitos commented on docs/docs/docs/max/micro-frontend.md
> +import { useState } from 'react';
同上

2023-09-06 02:53 UTC, kuitos commented on packages/plugins/libs/qiankun/slave/lifecycles.ts
> +          // 不再判断 autoSetLoading 的值，因为通过组件模式可以直接传递 loader
这里还是要的吧？loader 跟 autoSetLoading 不是互斥的配置

2023-09-06 02:55 UTC, gaopeng0108 commented on docs/docs/docs/max/micro-frontend.md
> +:::success{title=🏆︎} 本教程假设您对什么是微前端，什么是 Qiankun 微应用，以及如何使用 Qiankun 微应用已经有了基本的了解。 :::
这个是 prettier 自动保存搞出来的，我看看

2023-09-06 02:57 UTC, gaopeng0108 commented on packages/plugins/libs/qiankun/slave/lifecycles.ts
> +          // 不再判断 autoSetLoading 的值，因为通过组件模式可以直接传递 loader
也就是说配置了 loader 还是需要配置 autoSetLoading 的吗？

我看之前的模式中，即使配置了 loader，假如不配置 autoSetLoading，loader 里的 loading 也不会更新，一直会是 true

2023-09-06 03:08 UTC, gaopeng0108 commented on docs/docs/docs/max/micro-frontend.md
> +import { useRef } from 'react';
![image](https://github.com/umijs/umi/assets/22069371/73e9fc5b-8543-4e1b-b86c-faabcc473d60)

现在文档里很多地方都没有再显示声明了，感觉可以保持这样？

2023-09-06 06:38 UTC, kuitos commented on docs/docs/docs/max/micro-frontend.md
> +import { useRef } from 'react';
ok

2023-09-06 06:41 UTC, kuitos requested changes

2023-09-06 06:41 UTC, kuitos commented on packages/plugins/libs/qiankun/slave/lifecycles.ts
> +          // 不再判断 autoSetLoading 的值，因为通过组件模式可以直接传递 loader
是的。autoSetLoading 是用来标识子应用会自动改状态的，没配就需要用户手动调用 props.setLoading

2023-09-06 06:59 UTC, gaopeng0108 commented on packages/plugins/libs/qiankun/slave/lifecycles.ts
> +          // 不再判断 autoSetLoading 的值，因为通过组件模式可以直接传递 loader
![image](https://github.com/umijs/umi/assets/22069371/aa3c550c-6ba8-4f93-bb70-89743efb4c82)

我 get 你的意思了，但是之前传递给 loader 里面的只有 loading，那我补个 setLoading 的参数？

2023-09-06 10:48 UTC, fz6m commented
这个 PR 里怎么都是格式化的改动啊，很难 review ，建议做最小改动，不要大面积的格式化，一点也不清真，等下个人改代码又是一种风格。

2023-09-06 11:10 UTC, kuitos commented on packages/plugins/libs/qiankun/slave/lifecycles.ts
> +          // 不再判断 autoSetLoading 的值，因为通过组件模式可以直接传递 loader
没设置autoSetLoading说明他期望自己在子应用里控制loading状态

2023-09-06 15:04 UTC, gaopeng0108 commented
> 这个 PR 里怎么都是格式化的改动啊，很难 review ，建议做最小改动，不要大面积的格式化，一点也不清真，等下个人改代码又是一种风格。

1. 我用的是默认的 prettier 的格式化
2. 在改动的时候，有很多以前格式不太合理的地方，我觉得一起格式化掉也是合理的，比如说：
![image](https://github.com/umijs/umi/assets/22069371/4f370a2d-df2a-4fcb-a9e3-0625c5c936d5)
以前代码末尾不应该有空格，格式化之后去掉了
![image](https://github.com/umijs/umi/assets/22069371/3f9a6544-f307-4096-9ac2-9d2b5f53aa30)
以前有的有 React 声明，有的没有，格式化之后统一了
3. 我觉得个人代码风格有差异是 ok，重要是一个文件、模块、项目内部要保持一致

2023-09-07 02:12 UTC, gaopeng0108 reviewed
add autoSetLoading

2023-09-07 03:47 UTC, kuitos approved these changes
LGTM

2023-09-07 06:22 UTC, fz6m commented on docs/docs/docs/max/micro-frontend.md
> +export default function (loading: boolean) {
匿名组件会导致 HMR 失效。

2023-09-07 06:22 UTC, fz6m commented on docs/docs/docs/max/micro-frontend.md
> +// .app.tsx
```suggestion
// app.tsx
```

2023-09-07 06:23 UTC, fz6m commented on docs/docs/docs/max/micro-frontend.md
> +export default function (error: Error) {
同上，不要给匿名组件的例子。

2023-09-07 06:25 UTC, fz6m commented on docs/docs/docs/max/micro-frontend.md
> +注意：`loader` 的优先级高于 `defaultLoader`。
这里写一个区块说明下哪个版本到哪个版本有 `master.loader` 选项被删除了吧，这是 Breaking change ，偷偷就删了要说一下：

```ts
:::info{title=...}
...
:::
```

2023-09-07 07:18 UTC, gaopeng0108 commented on docs/docs/docs/max/micro-frontend.md
> +注意：`loader` 的优先级高于 `defaultLoader`。
master.loader 是刚开出去的，目给内部用户用的，并且还在联调阶段，所以就没有说明

2023-09-07 07:54 UTC, stormslowly approved these changes

2023-09-07 07:55 UTC, merged

2023-09-07 08:34 UTC, gaopeng0108 commented on docs/docs/docs/max/micro-frontend.md
> +export default function (loading: boolean) {
https://github.com/umijs/umi/assets/22069371/648f926b-6a0f-4526-bf07-c30928abf2ed

我验证了一下，好像并不存在你说的问题

2023-09-07 08:36 UTC, gaopeng0108 commented on docs/docs/docs/max/micro-frontend.md
> +// .app.tsx
ok 后面改下

2023-09-08 04:24 UTC, fz6m commented on docs/docs/docs/max/micro-frontend.md
> +export default function (loading: boolean) {
在大型应用里匿名组件一定会 HMR 失效，匿名组件是 react refresh webpack plugin 明确禁止的一种写法。