fix: add layout file when collect ssr loader
umijs/umi pull request #11666
Opened 2023-09-20 10:08 UTC by ppppp-x-x

### Background
解决在收集 ssr 路由相关信息时遗漏 layout 文件的问题
目前在编译时收集路由 serverLoader 时只包含了页面文件，layout 文件也需要支持配置 serverLoader、clientLoader
### Solution
- 改变收集数据的位置，调整到 add layout 之后执行

2023-09-20 18:52 UTC, fz6m approved these changes

2023-09-20 18:56 UTC, fz6m requested changes
自己排查下 CI 吧，这个时候 layout 可能还没生成出来。

2023-09-22 02:19 UTC, ppppp-x-x commented
> 自己排查下 CI 吧，这个时候 layout 可能还没生成出来。

好的，我排查一下 CI～但是“这个时候 layout 可能还没生成出来”请问下是什么意思呢，我看这里 layout 已经 add 进去了

2023-09-22 21:55 UTC, fz6m commented
我看有的报错是检查文件存在性失败了，目测有的 layout 是由插件生成的临时文件作为 layout ，这个 collect 的时候可能 layout 文件可能还没生成出来。

2023-09-23 09:20 UTC, ppppp-x-x commented
> 我看有的报错是检查文件存在性失败了，目测有的 layout 是由插件生成的临时文件作为 layout ，这个 collect 的时候可能 layout 文件可能还没生成出来。

我排查了下，这里应该是因为我调整了 routes 中的“layout”，为它增加了 hasServerLoader | clientLoader | routeProps 导致 jest snapshot 与之前生成的不一致导致的
如果要 layout 文件也支持 export serverLoader ｜clientLoader 的话，这里是否可以给 routes => layout 添加这些属性呢～如果可以的话，需要更新下测试快照

2023-09-23 18:40 UTC, fz6m commented
可以，改了看一下。

2023-09-25 00:49 UTC, fz6m commented
还是有问题，再检查下 CI

2023-09-25 01:41 UTC, sorrycc commented
ci 还是有问题，我看了下第一个是「ENOENT: no such file or directory, open '/home/runner/work/umi/umi/examples/max/.umi-production/plugin-layout/Layout.tsx'」，得排查下原因看。可能的原因是，可能有些虚拟文件已经有 __content 等信息了，不需要读文件系统。

2023-09-25 17:01 UTC, ppppp-x-x commented
> 还是有问题，再检查下 CI

好的～

2023-09-26 02:08 UTC, sorrycc approved these changes

2023-09-26 02:08 UTC, merged