SSR适配ER render
umijs/umi pull request #11698
Opened 2023-09-28 07:31 UTC by gwuhaolin

- createUmiHandler只返回根节点的内容，不要返回整个 html 的
- SSR输出的server.js路径带上hash
- server.js中的build-manifest.json文件路径支持SSR_RESOURCE_DIR环境变量

2023-09-28 07:42 UTC, PeachScript commented on packages/preset-umi/templates/server.tpl
> +  process.env.UNIO_RESOURCE_DIR ? process.env.UNIO_RESOURCE_DIR + '/build-manifest.json' :
`UNIO` -> `SERVER`？框架读取的环境变量尽量通用化

2023-09-29 03:49 UTC, fz6m requested changes

2023-09-29 03:49 UTC, fz6m commented on packages/renderer-react/src/server.tsx
> +  if (opts.withoutHTML) return app;
```suggestion
  if (opts.withoutHTML) {
    return app;
  }
```

2023-09-29 03:49 UTC, fz6m commented on packages/preset-umi/src/features/ssr/webpack/webpack.ts
> +      .filename('[name].[hash:8].server.js')
应该当用户开启了 `userConfig.hash && !isDev` 的时候才带 hash ，可参考 `packages/bundler-webpack/src/config/config.ts`

```ts
  const useHash = !!(opts.hash || (userConfig.hash && !isDev));

    // ...
    .filename(useHash ? `[name].[contenthash:8].js` : `[name].js`)
    .chunkFilename(
      useHash ? `[name].[contenthash:8].async.js` : `[name].async.js`,
    )
```

2023-09-29 03:49 UTC, fz6m commented on packages/preset-umi/src/features/ssr/webpack/webpack.ts
>        .chunkFilename('[name].server.js')
`chunkFilename` 也应该改吧。

2023-09-29 03:49 UTC, fz6m commented on packages/preset-umi/src/features/ssr/webpack/webpack.ts
> +      .filename('[name].[hash:8].server.js')
需要排查 `packages/preset-umi/src/features/ssr/utils.ts` 中 `absServerBuildPath` 方法定义的 `umi.server.js` 是否有影响。

2023-09-29 03:49 UTC, fz6m commented on packages/preset-umi/src/features/ssr/webpack/webpack.ts
> +      .filename('[name].[hash:8].server.js')
需要修订 `packages/preset-umi/src/features/ssr/ssr.ts` 中因路径变化导致 vercel api 功能的影响：

```ts
  if (api.config.ssr.platform === 'vercel') {
  // 修订...
```

2023-09-29 03:49 UTC, fz6m commented on packages/preset-umi/src/features/ssr/webpack/webpack.ts
> +      .filename('[name].[hash:8].server.js')
需要确认 `packages/bundler-webpack/src/config/miniCSSExtractPlugin.ts` 中以下逻辑的影响：

```ts
  chunkFilename: opts.userConfig.ssr
          ? // TODO: FIXME
            `umi${hash}.css`
          : `[name]${hash}.chunk.css`,
```

因为之前的实现固定只有一个 `umi` 入口和 chunk ，但现在改为 `[name]` 可能存在影响。

2023-09-29 03:49 UTC, fz6m commented on packages/preset-umi/src/features/ssr/webpack/webpack.ts
> +      .filename('[name].[hash:8].server.js')
需要确认 `examples/{ssr-demo, ssr-demo-2, ssr-webpack, ssr-todos}` 这几个 example 的状态，开发和构建后是否均正常。

2023-09-29 03:49 UTC, fz6m commented on packages/preset-umi/src/features/ssr/webpack/webpack.ts
> +      .filename('[name].[hash:8].server.js')
需要确认对 dumi 相关 `ssr: {}` 和 `exportStatic: {}` 的影响。

2023-09-29 03:49 UTC, fz6m commented on packages/preset-umi/templates/server.tpl
> +  process.env.UNIO_RESOURCE_DIR ? process.env.UNIO_RESOURCE_DIR + '/build-manifest.json' :
建议使用 `process.env.UMI_MANIFEST_DIR`

2023-10-06 11:50 UTC, fz6m commented on packages/server/src/ssr.ts
> -          stream.pipe(writable);
这个地方改成直接返回 stream 的话，就没有 `onShellReady` 了，就检测不到什么时候渲染结束吧，是不是还需要透传下用户可能给的 options ？

`ReactDomServer.renderToReadableStream(..., { /* ...userOptions */ })`

2023-10-07 01:59 UTC, gwuhaolin commented on packages/preset-umi/src/features/ssr/webpack/webpack.ts
> +      .filename('[name].[hash:8].server.js')
<img width="1651" alt="image" src="https://github.com/umijs/umi/assets/5773264/4b665260-0881-4a90-9a01-d81ef149e5bb">
<img width="1745" alt="image" src="https://github.com/umijs/umi/assets/5773264/b97b2960-11c0-46db-b369-39cdc314e1bf">
看上去没问题

2023-10-07 02:01 UTC, PeachScript commented on packages/server/src/ssr.ts
> -          stream.pipe(writable);
在静态站点场景下 html 产物里需要预填充 ssr 后完整的 DOM 结构，这里改成 stream 输出应该会影响产物内容，得区分一下 exportStatic 模式和 ssr 模式的返回结果

2023-10-07 02:03 UTC, gwuhaolin commented on packages/server/src/ssr.ts
> -          stream.pipe(writable);
看官方文档，renderToReadableStream 返回的就是 [Readable Web Stream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream)，ER用 Response包裹后内部会处理渲染结束事件。
这是官方demo：
https://react.dev/reference/react-dom/server/renderToReadableStream#usage

2023-10-07 02:11 UTC, PeachScript commented on packages/server/src/ssr.ts
> -          stream.pipe(writable);
ER 用 stream 没问题，但 umi exportStatic 需要的是字符串，相关逻辑在这里：https://github.com/umijs/umi/blob/ca168e953542aa38b9318c2645bee73da20b3e3e/packages/preset-umi/src/features/exportStatic/exportStatic.ts#L67

所有需要区分返回值避免原有逻辑不受影响

2023-10-07 02:15 UTC, PeachScript commented on packages/server/src/ssr.ts
> -          stream.pipe(writable);
确认不影响 exportStatic 特性，这里的逻辑改动在 createUmiHandler 中，前者依赖的是 createMarkupGenerator

2023-10-07 03:14 UTC, sorrycc approved these changes

2023-10-07 03:15 UTC, merged