feature: SSR模式下，多输出一份和index.html完全一致的*.html文件，用于ER场景
umijs/umi pull request #11723
Opened 2023-10-11 08:25 UTC by gwuhaolin

2023-10-11 08:29 UTC, gwuhaolin commented
<img width="842" alt="image" src="https://github.com/umijs/umi/assets/5773264/c9d672cd-7db5-4443-9c47-833819f04081">
如图会输出两个一样的html文件

2023-10-11 08:31 UTC, sorrycc requested changes

2023-10-11 08:31 UTC, sorrycc commented on packages/preset-umi/src/commands/build.ts
> +          if (api.config.ssr && path === 'index.html') {
放在 ssr.ts 里，在 api.onBuildSuccess 里 fs copy output/index.html 为 *.html 。

2023-10-11 09:05 UTC, sorrycc approved these changes

2023-10-11 09:05 UTC, merged

2023-10-11 10:52 UTC, fz6m commented on packages/preset-umi/src/features/ssr/ssr.ts
> +    fsExtra.copyFileSync(join(api.paths.absOutputPath, 'index.html'), join(api.paths.absOutputPath, '*.html'));
这个地方非常不清真。

1. 首先这是用户非预期的文件，我们不应该生成大部分用户不需要的文件，这部分特定于 serverless 的可以做到 bigfish 里或者单独的 serverless plugin 或 preset 里去，而不应该污染源代码库造成所有人都有这个副作用。

2. 其次有的人可能对 html 产物做了修改，这里复制了 `index.html` 其实用户会得到两个不一样的 html 产物，会造成非常大的疑惑，是黑盒。

3. 另外标准存在不一致，社区内对于 404 fallback 的默认行为是 找不到会使用 `404.html` ，而这里是 `*.html` ，不符合社区共识。

### 改进意见

1. 做到 bigfish 中或内部自己的 serverless umi plugin or preset 中，不要污染 umi 代码仓库造成所有人的副作用和非预期黑盒产物。

或

2. 新增选项 `ssr: { er: true }` 选项来开启这个生成功能，以后所有的副作用做到这个选项开启内。

2023-10-13 10:05 UTC, yoyo837 commented
`*.html`是Windows不兼容的文件路径, 这破坏了 `antd` 的CI build.