feature: 支持在serverLoader中读取当前request，以实现在serverLoader中读取url中的参数和headers
umijs/umi pull request #11755
Opened 2023-10-18 02:05 UTC by gwuhaolin

2023-10-18 02:29 UTC, sorrycc requested changes
1、request 给一个 Request instance 吧，参考 https://developer.mozilla.org/en-US/docs/Web/API/Request
2、接口用 object 的形式，比如 serverLoader({ request })，方便后续扩展 params 和 context 等功能
3、umi 里新增一个 LoaderArgs 的类型，方便通过 import type {LoaderArgs} from 'umi'; async function serverLoader({ request }: LoaderArgs) {} 确保类型正确。

2023-10-18 04:27 UTC, fz6m commented on packages/server/src/ssr.ts
> +  return await mod.serverLoader(req);
`async` 函数返回值不需要 await ，不然会多造成一次异步成本。

2023-10-18 04:27 UTC, fz6m commented on packages/server/src/ssr.ts
> +  return await mod.serverLoader(req);
需要给 `mod.serverLoader` 一个类型，减少后续维护成本：

```ts
interface IServerLoaderExecParams {
  request: Request
}

// ...

  return mod.serverLoader({ request });
```

先想清楚了这里以后是不是还要传其他的东西进来，今天要 req 明天又要 res 大后天又要新的要改一万次。

2023-10-18 04:27 UTC, fz6m commented on packages/server/src/ssr.ts
> +  req: Request
匿名参数太多了，考虑到想不清楚后续参数既要又要改，这里应该换成对象传参，需新增类型：

```ts
interface IExecuteLoaderParams {
  routeKey: string
  routesWithServerLoader: RouteLoaders
  request: Request
}
```

此处应该使用 `request` 而不是 `req` ，更具体一点方便阅读。

2023-10-18 04:27 UTC, fz6m commented on packages/server/src/ssr.ts
> +    return await executeLoader(query.route, opts.routesWithServerLoader, req);
想清楚是不是只要 `req` ，以后哪天会不会要新的，到时候又要改了重新发布，可能要的稳定性变量一起都传进来，一个参考：

```ts
  executeLoader({
    routeKey,
    routesWithServerLoader,
    // 此处还应提取为 `IExecuteLoaderData`
    loaderData: { 
      request: Request,
      // ... 
    }
  })
```

2023-10-18 04:27 UTC, fz6m commented on packages/server/src/ssr.ts
> +    const jsx = await jsxGeneratorDeferrer(req.url, req.headers);
这行改动是啥意思，貌似没影响到啥。

2023-10-18 04:27 UTC, fz6m commented on packages/server/src/ssr.ts
> +              } as Request);
打算从哪里传递 `(url: string, headers?: Headers)` 里的第二个参数，没看到传的地方，确定好传递位置后注意补全类型，另外这里 `{ url, headers }` 是不完全的，当确定是一部分时，需要编写新的类型：

```ts
  type UmiRequest = Partial<Request> & Pick<Request, 'url' | 'headers' | ...>
```

2023-10-18 04:35 UTC, fz6m commented
类型补全建议，在 ssr 插件里写一个 `types.d.ts` 文件（这个文件会自动 export 可用）导出类型：

1. `serverLoader` 类型，示例：

```ts
import { IServerLoader } from 'umi'

export const serverLoader: IServerLoader = ({ request , ... }) => {}
```

2. 补充 `useServerLoaderData` 的类型，完成效果示例：

```ts
export const serverLoader = () => {}

// ...

  // 正确获取到 serverLoader 的返回值
  const data = useServerLoaderData<typeof serverLoader>()
```

2023-10-18 06:17 UTC, sorrycc requested changes

2023-10-18 06:17 UTC, sorrycc commented on packages/server/src/ssr.ts
> +  // 需要从req中读取url、header等
注意盘古之白。

2023-10-18 06:44 UTC, gwuhaolin commented on packages/server/src/ssr.ts
> +  return mod.serverLoader(serverLoaderArgs);
async 函数返回值不需要 await ，不然会多造成一次异步成本。

2023-10-18 10:09 UTC, PeachScript commented on packages/server/src/ssr.ts
> +    const { pathname } = new URL(url);
这里更改入参的类型会影响已有的构建时预渲染功能（exportStatic + ssr），因为构建时预渲染传入的是不带 origin 的 pathname，比如 `/home`，这里 new URL 就会报错

建议方案：`headers?: Headers` => `opts?: { request: Request }`，在外部把 `request` 构造好（也可以直接复用 middleware 收到的 Request？）再传进来给 executeLoader 作为入参，这样 jsxGenerator 内部的 url 值类型可以保持不变

2023-10-19 07:24 UTC, sorrycc approved these changes

2023-10-19 07:25 UTC, merged

2023-10-19 09:03 UTC, fz6m commented on packages/server/src/ssr.ts
> +// serverLoader的参数类型
如果用 `// xxx` ，是给源码里看的，如果用 `/* xxx */` ，则用户 hover 上去也能看到，所以最好用后者，这样才能给用户更好的类型提示，一个优雅的编写参考：

```ts
/**
 * 类型是做什么的
 */
interface IArgs {
  /**
   * a 有啥用
   */
  a: string
  /**
   * b 有啥用
   */
  b: number
}
```

2023-10-19 09:05 UTC, fz6m commented on packages/server/src/ssr.ts
> +export interface IServerLoaderArgs {
不要乱导出东西，啥都导出去是不对的，外面用不到 、现在不需要被其他文件引用 的东西不应该无脑 `export` ，这样后面会留坑，另外乱 export 很可能造成循环引用，因为这个类型只在这个文件使用了，所以不应该导出。

2023-10-19 09:08 UTC, fz6m commented on packages/server/src/ssr.ts
> +        { request: req },
这样写是很不清真的，而且反复写了三次，以下是两种正确的优雅书写方式参考：

```ts
const loaderArgs: IServerLoaderArgs = {
  request: req
}

// use loaderArgs
```

或

```ts
  { request: req } satisfies IServerLoaderArgs
```

2023-10-19 09:14 UTC, fz6m commented on packages/server/src/ssr.ts
> +    const request = new Request(req.protocol + '://' + req.get('host') + req.originalUrl, {
为啥要用 `req.originalUrl` ，很奇怪，很少见，用 `req.pathname` 不行吗。

2023-10-19 09:15 UTC, fz6m commented on packages/server/src/ssr.ts
> +    const request = new Request(req.protocol + '://' + req.get('host') + req.originalUrl, {
真的丑陋，这辈子最好都不要用 `+` 号拼接字符串，拼接字符串的唯一方式只有模板字符串。

2023-10-19 09:19 UTC, fz6m commented
希望新开一个 PR 修复上述建议中的细节，提升优雅程度，这个文件越改越屎了，甚至没有格式化。

1. 参考上述评论修正细节修正后格式化一下文件。

2. 【可选】：你的 request 并不是完美的 request ，需要正确的 request 类型而不是无脑 `Request` ：

```ts
  type UmiRequest = Partial<Request> & Pick<Request, 'url' | 'headers' | ...>
```

3. 【支线任务】：`serverLoader 类型，实例参考上面的评论。

4. 【支线任务】：补充 `useServerLoaderData` 的类型，参考上面的评论。

2023-10-19 09:24 UTC, fz6m commented
另外这个 PR https://github.com/umijs/umi/pull/11724#discussion_r1354716494 中的优化也建议做下。