fix(examples): 静态资源加载错误
umijs/umi pull request #11980
Opened 2023-12-21 07:45 UTC by wangz-code

mac m1 
info  - dumi v2.2.16
info  - Umi v4.0.89

如果先执行umi.server.js  会导致页面样式错误,  控制台提示:
```  Uncaught SyntaxError: Unexpected token '<' ```

2023-12-21 17:31 UTC, fz6m commented
因为时间太久，这个 `ssr-todos` 示例我也不知道怎么用的了，里面需要启动一个 todo api 的服务，并且涉及到 `isomorphic-unfetch` 的关联上游 `unfetch` 导出错误，以及 `node:` 的替换问题，现在这个 example 是启动不了也构建不了的。

如有兴趣，可以重写一下这个 example ，把 vercel 的部分去掉，换成本地 express mock 的 todo api 服务，删除 `isomorphic-unfetch` 。

2023-12-27 06:56 UTC, wangz-code commented
> 因为时间太久，这个 `ssr-todos` 示例我也不知道怎么用的了，里面需要启动一个 todo api 的服务，并且涉及到 `isomorphic-unfetch` 的关联上游 `unfetch` 导出错误，以及 `node:` 的替换问题，现在这个 example 是启动不了也构建不了的。
> 
> 如有兴趣，可以重写一下这个 example ，把 vercel 的部分去掉，换成本地 express mock 的 todo api 服务，删除 `isomorphic-unfetch` 。

简单改了一版, 不确定是否符合你的意思
- 使用 axios 替换了  isomorphic-unfetch 主要用于 node环境下发起请求
- dev 使用umi中间件mock api
其他的基本保持一致 
我调试的时候发现 useServerLoaderData  加载数据时总是读取旧数据, 不确定是不是bug

2023-12-29 00:00 UTC, fz6m requested changes

2023-12-29 00:00 UTC, fz6m commented on examples/ssr-todos/production-server.js
> +app.post('/api/todos_update',function (req, res) {
这部分接口逻辑是不是和 `plugin` 里重复的啊，重复的部分写成 js 复用起来吧，在 `production-server.js` 和 `plugin.ts` 间。

2023-12-29 00:01 UTC, fz6m commented on examples/ssr-todos/package.json
> -    "isomorphic-unfetch": "^4.0.2",
改动依赖要更新 lock 文件，你同步一下上游仓库变更，之后和 `upstream/master` 合并下，之后 `pnpm i` 更新下 lock 文件就可以。

2024-01-01 01:01 UTC, fz6m commented
真感觉这里面以前写的历史代码一塌糊涂啊，我先简单改了改，真要写一个优雅的 todo list ，react-query 、loading 、组件库这些都不能少，先简单能用就行吧，感谢你的 PR 。

2024-01-01 01:19 UTC, merged