[WIP] feat: support to preload route chunk files
umijs/umi pull request #12095
Opened 2024-01-25 04:15 UTC by PeachScript

支持根据访问路由预加载子路由 chunk 文件，主要改动点：
1. okam 增加设置 `api.appData.bundler` 的逻辑，用于标记预加载脚本
2. routePrefetch 支持通过 stats 及 routes 信息产出路由 chunk 资源映射表，用于预加载
3. routePrefetch 增加 `preload: 'script' | 'map'` 子配置项，其中 `script` 模式会在 HTML 产物中插入 inline script，该 script 会根据访问路由自动添加 async script 标签和 preload link 标签预加载访问该子路由需要的所有资源（不含子路由渲染逻辑内的异步加载资源）；而 `map` 模式则会输出路由资源映射表，配合 Umi 提供的方法可以在微前端等场景实现自定义的资源预加载

暂时先不合并，先在分支上发 canary 用于验证

2024-02-27 09:08 UTC, sorrycc requested changes

2024-02-27 16:21 UTC, fz6m commented on packages/preset-umi/src/features/routePreloadOnLoad/utils.ts
> +  type: 'js' | 'css' | unknown;
有固定字符串，并允许任意字符串，同时支持类型提示的方法，用其他的方法是没有类型提示的：

```ts
  type: 'js' | 'css' | (string & {})
```

2024-02-27 16:21 UTC, fz6m commented on packages/preset-umi/src/client/preloadRouteFilesScp.ts
> +      tag.async = true;
这里一进来就会和图片什么的争下载带宽吧，用 link 标签做 script 的 prefetch 是不是更好，等空闲时让他自己去加载（假如是手动预加载，就是 preload 高优先级）。

下面的 style 也是一样，preload 的优先级比较高，一进页面就会和其他图片之类的抢带宽。

2024-02-27 16:23 UTC, fz6m commented on packages/preset-umi/src/client/preloadRouteFilesScp.ts
> +      tag.async = true;
另外我了解到，最好给 prefetch 添加 `as` 声明，给 preload 添加 `as` 和 `crossorigin` 声明，不然可能造成资源二次下载。

2024-02-28 01:40 UTC, PeachScript commented on packages/preset-umi/src/features/okam/okam.ts
> +    enableBy: () => Boolean(process.env.OKAM),
整合的话似乎只能挂 service 上，消费的地方都能拿到 api

2024-02-28 02:13 UTC, PeachScript commented on packages/preset-umi/src/features/routePreloadOnLoad/utils.ts
> +    const id = map.f[i][1];
index 即插入顺序，ES6 开始对象的字符串 key 顺序应该是等同于插入顺序的

2024-02-28 02:21 UTC, PeachScript commented on packages/preset-umi/src/client/preloadRouteFilesScp.ts
> +      tag.async = true;
script 用 async 提前载入是有意为之的，因为 prefetch 只是预取资源，js 代码的解释和执行仍然是滞后的，但这个 feature 是希望在不阻塞 entry 的情况下尽可能早地把子路由需要的 js 模块都初始化完毕

css 用 preload 是因为这是当前路由渲染的必要 CSS，比图片载入的优先级应该更高


> 给 preload 添加 `as` 和 `crossorigin` 声明，不然可能造成资源二次下载。

这个有相关文档链接么，我查了下 MDN 只提到 `as` 为 `font` 或 `fetch` 时需要设置 `crossorigin` https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload

2024-02-28 02:24 UTC, PeachScript commented on packages/preset-umi/src/features/routePreloadOnLoad/routePreloadOnLoad.ts
> +                  : current.file!.replace(/^(\.\/)?/, './');
改了下正则，已覆盖到 `../` 的 case

2024-02-28 07:29 UTC, fz6m commented on packages/preset-umi/src/client/preloadRouteFilesScp.ts
> +      tag.async = true;
你说的应该是对的，我在 [这篇文章](https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf) 看到了 `as` 声明的必要性，会影响到优先级，`crossorigin` 应该只需要对 font 添加。

另外这里 async 的脚本假如在执行过程中，主 entry 加载到这个 module 了咋办，此时内容不是完整的会出现问题吧，因为不是 webpack 管理的加载流程，并且 async 执行是全随机时间的，我认为会导致存在竟态问题。

2024-02-28 07:32 UTC, fz6m commented on packages/preset-umi/src/features/routePreloadOnLoad/utils.ts
> +    const id = map.f[i][1];
在构造 `f` 的时候，没有显示的按照 `index` 进行排序，对于不同的 js 引擎和环境以及优化机制的不确定性，我认为应该明确的做一次排序构造，而不是依赖某些隐性不确定的顺序。

2024-02-28 08:40 UTC, PeachScript commented on packages/preset-umi/src/client/preloadRouteFilesScp.ts
> +      tag.async = true;
这个脚本插入的 script 标签上有 webpack/mako 的标记，当 webpack/mako 需要异步加载一个 chunk 的时候，会先从 DOM 中查找是否已经存在 script，如果有则会直接监听它的 `onload` 不会重新插入新的脚本，所以不会发生冲突

2024-02-28 09:17 UTC, PeachScript commented on packages/preset-umi/src/features/routePreloadOnLoad/utils.ts
> +    const id = map.f[i][1];
在主流实现中顺序应该都是稳定的，但遍历顺序的确不是规范的一部分，已加上 sort，ref: https://stackoverflow.com/a/280861

2024-02-28 09:18 UTC, fz6m commented on packages/preset-umi/src/features/routePreloadOnLoad/routePreloadOnLoad.ts
> +                    current.file.replace(/^([^.]|\.[^./])/, './$1');
这个正则应该是错的，比如 `.aa` 转换成 `./a` 了，感觉变复杂了，可以使用 [regex101](https://regex101.com/) 帮助分析。

2024-02-29 01:44 UTC, sorrycc approved these changes

2024-02-29 01:45 UTC, merged

2024-02-29 06:13 UTC, fz6m commented
由于 `package.json#name` 绝大部分项目基本都有，所以这个 PR 对所有人默认都开启了，这影响到第一次进入页面的加载，每个人都会预加载，后续可以持续关注下有没有问题。

2024-03-25 11:36 UTC, zkp442910864 commented
可以增加个开关吗？
加了这个好像导致使用微前端的时候，产生错误请求，使用相对路径的时候

2024-03-25 14:44 UTC, PeachScript commented
> 可以增加个开关吗？ 加了这个好像导致使用微前端的时候，产生错误请求，使用相对路径的时候

可能是脚本插入到 qiankun 改 publicPath 的脚本后面了，ref: https://github.com/umijs/umi/blob/56313d47c0d60d5fe124e0a04bdcba1135d33b78/packages/plugins/src/qiankun/slave.ts#L177

有空的话帮忙验证下上面的猜想，如果确认欢迎提个 PR 调整下 preload 插件插入 headScripts 的钩子 stage 优先级，可以挪到最后面

2024-03-26 07:31 UTC, zkp442910864 commented
> > 可以增加个开关吗？ 加了这个项目导致使用微前端的时候，产生错误请求，使用相对路径的时候
> 
> 可能是脚本添加到 qiankun 修改 publicPath 的脚本后面了，ref:
> 
> https://github.com/umijs/umi/blob/56313d47c0d60d5fe124e0a04bdcba1135d33b78/packages/plugins/src/qiankun/slave.ts#L177
> 
> 有空的话帮忙验证下上面的猜想，如果确认欢迎提个 PR 调整下 preload 插件插件 headScripts 的钩子阶段优先级，可以挪到最后面

我本地开启nginx 测试了下，换了个位置后，错误信息没有提示出来了
pr提交了，请检查下
https://github.com/umijs/umi/pull/12234

2024-06-20 07:46 UTC, consistent-k commented
> > > 可以增加个开关吗？ 加了这个项目导致使用微前端的时候，产生错误请求，使用相对路径的时候
> > 
> > 
> > 可能是脚本添加到 qiankun 修改 publicPath 的脚本后面了，ref:
> > https://github.com/umijs/umi/blob/56313d47c0d60d5fe124e0a04bdcba1135d33b78/packages/plugins/src/qiankun/slave.ts#L177
> > 
> > 有空的话帮忙验证下上面的猜想，如果确认欢迎提个 PR 调整下 preload 插件插件 headScripts 的钩子阶段优先级，可以挪到最后面
> 
> 我本地开启nginx 测试了下，换了个位置后，错误信息没有提示出来了 pr提交了，请检查下 #12234

我部署的代码验证还是有问题。主应用base为 /base-web，publicPath为：/static-base-web/  子应用base为 /child-web，publicPath为：/static-child-web/ 升级到最新版umi后发现预加载子应用的js和css 都是不带/static-child-web/的 导致控制台看起来一大片404。于是回退umi到4.1.5版本 发现功能正常 不会有预加载的404  求问如何解决