feat: support react/jsx-runtime
umijs/umi pull request #12219
Opened 2024-03-19 13:20 UTC by Wu-kung

支持  React 16.14.0 版本以上使用全新的转换，可以单独使用 JSX 而无需引入 React。

2024-03-20 00:31 UTC, fz6m commented
有这个需求的原因是啥，你们有 v16.14+ 的项目在用 umi 4 吗，我理解不是升级的项目的话， umi 4 的项目已经绝大多数都是 18 或 17 了。

2024-03-20 01:28 UTC, sorrycc commented
@fz6m 背景是，之前内网答疑同学遇到的，老项目升级，可能由于加了 babel 插件没有写 `import React from 'react';`，升级过来后没有写这句会报错，因为是 react 16。

2024-03-20 05:51 UTC, fz6m approved these changes

2024-03-21 01:56 UTC, sorrycc requested changes

2024-03-21 01:56 UTC, sorrycc commented on packages/preset-umi/src/commands/dev/dev.ts
> +      const isGTEReact16 =
isGTEReact16 > shouldUseAutomaticRuntime

2024-03-22 05:42 UTC, sorrycc approved these changes

2024-03-22 05:42 UTC, merged