feat: Add react 18 support
umijs/umi pull request #8031
Opened 2022-04-18 11:30 UTC by ken20001207

增加了 React 18 的支持。

### 解决方案

让 `renderer-react` 构建两种不同版本的产物 (`index.js` 和 `index18.js`)，其中 `index18.js` 中对 React 18 的新 API （例如 `createRoot`, `hydrateRoot`）提供了支持。

在 `tmpFiles` 中，根据 `api.pkg` 中是否有 React 依赖，有的话检查版本是否为 18，是的话就选用 `index18.js` 作为 renderer 。

### 效果

可以使用 `yarn example dev examples/react-18` 测试效果。

<img width="703" alt="Screen Shot 2022-04-18 at 7 28 29 PM" src="https://user-images.githubusercontent.com/21105863/163801952-b1c53874-3556-4ef9-858b-40335e7bdfa2.png">

<img width="797" alt="Screen Shot 2022-04-18 at 7 26 16 PM" src="https://user-images.githubusercontent.com/21105863/163801726-d1b6ba3c-05e6-408d-822a-58e56321b225.png">

2022-05-05 12:45 UTC, curtu commented
any info about this? thank you

2022-05-06 09:08 UTC, ken20001207 commented
Moved to #8071 .

2022-05-10 04:27 UTC, PeachScript commented
@ken20001207 @sorrycc 这个 PR 还缺啥吗

2022-05-10 04:36 UTC, PeachScript requested changes

2022-05-10 04:36 UTC, PeachScript commented on packages/preset-built-in/src/plugins/generateFiles/umi.ts
> +    let isReact18 = !!(api.pkg.dependencies || {})['react']?.match(/^\^?18/);
还有 `~`、`>`、`>=` 的情况，最好从 cwd require `react/package.json` 直接拿安装好的版本，然后用 api.utils.semver 来匹配

2022-05-10 04:36 UTC, PeachScript commented on packages/renderer-react/package.json
> +    "react-18": "npm:react@^18.0.0",
这两个应该用项目安装的版本，这里不用声明？

2022-05-11 06:37 UTC, ken20001207 commented on packages/preset-built-in/src/plugins/generateFiles/umi.ts
> +    let isReact18 = !!(api.pkg.dependencies || {})['react']?.match(/^\^?18/);
@PeachScript 改好了 👍

2022-05-11 06:37 UTC, ken20001207 commented on packages/renderer-react/package.json
> +    "react-18": "npm:react@^18.0.0",
@PeachScript 改好了 👍

2022-05-18 07:00 UTC, PeachScript commented on packages/preset-built-in/src/plugins/generateFiles/umi.ts
> +          join(opts.cwd, 'node_modules', name, 'package.json'),
切 `APP_ROOT` 的场景下会不会有问题

2022-05-18 07:16 UTC, merged

2022-05-19 03:16 UTC, PeachScript commented on packages/preset-built-in/src/plugins/generateFiles/umi.ts
> +  const useCustomReact =
下面有读 version 的逻辑，但可能有问题还得改改