fix: get preload key always ends with css
umijs/umi pull request #8378
Opened 2022-07-04 15:31 UTC by KieSun

如果 `window.__umi_manifest__` 为以下代码：

```js
window.__umi_manifest__ = {
  "umi.css": "/umi.aa4342fc.css",
  "umi.js": "/umi.ffdad893.js",
  "1.css": "/1.f5fecf30.chunk.css",
  "1.js": "/1.57fecd0a.async.js",
  "2.css": "/2.f5fecf30.chunk.css",
  "2.js": "/2.0f29443f.async.js",
  "3.css": "/3.f5fecf30.chunk.css",
  "3.js": "/3.405c6284.async.js",
  "4.css": "/4.f8550f09.chunk.css",
  "4.js": "/4.3a0a27b4.async.js",
  "@@_global_layout.js": "/@@_global_layout.fb948677.async.js",
  "258.1df5da00.async.js": "/258.1df5da00.async.js",
  "62.02fa153b.async.js": "/62.02fa153b.async.js",
  "37.fd560c60.async.js": "/37.fd560c60.async.js",
  "376.009af299.async.js": "/376.009af299.async.js"
}
```

那么 `Object.keys(manifest)` 获得的数组中 css 文件名永远在 js 文件名之前，这样就导致 `k.startsWith(routeIdReplaced + '.')` 一直获得是 css 文件名。

2022-07-06 08:36 UTC, sorrycc requested changes
1、想了下，css 和 js 其实都需要 preload
2、如果只处理 js，可以在原来的基础上加一个 k.endsWith('.js')，尽量不用正则，不容易懂

2022-07-06 08:38 UTC, KieSun commented
> 1、想了下，css 和 js 其实都需要 preload 2、如果只处理 js，可以在原来的基础上加一个 k.endsWith('.js')，尽量不用正则，不容易懂

对的，确实也需要加载 css。用了正则主要是看到有 hash 的文件需要 preload，没有的话我就改回去。

2022-07-11 01:53 UTC, KieSun commented
@sorrycc 修改好了

2022-07-11 09:16 UTC, sorrycc commented on packages/renderer-react/src/browser.tsx
> +              if (!keys.length) return;
这行不需要了。

2022-07-11 09:18 UTC, sorrycc commented on packages/renderer-react/src/browser.tsx
> +                  link.as = 'script';
css 时用 style？参考：https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attributes

2022-07-11 09:19 UTC, sorrycc commented on packages/renderer-react/src/browser.tsx
> +                  link.as = 'script';
非 css 或 js 可以先不支持，直接 throw Error 就好。

2022-07-11 13:48 UTC, sorrycc commented on packages/renderer-react/src/browser.tsx
> +                if (!supportFile.includes(key)) {
这个逻辑感觉有问题。

2022-07-12 03:37 UTC, fz6m commented on packages/renderer-react/src/browser.tsx
> +                if (!key.match(/.(js|css)$/)) {
```suggestion
                if (!/\.(js|css)$/.test(key)) {
```

2022-07-12 07:53 UTC, sorrycc approved these changes

2022-07-12 07:53 UTC, merged