fix: 直接创建目录
umijs/umi pull request #8379
Opened 2022-07-04 23:10 UTC by txp1035

2022-07-04 23:13 UTC, txp1035 commented
![231](https://user-images.githubusercontent.com/9554297/177224387-4515bebf-30c6-4148-9a2b-abc1c237d83b.gif)

2022-07-04 23:19 UTC, txp1035 commented
![112](https://user-images.githubusercontent.com/9554297/177224692-ad6ec535-f6d9-4573-adc8-97005ee47f8c.gif)

2022-07-04 23:19 UTC, txp1035 commented
影响包：create-umi  、create-father

2022-07-04 23:30 UTC, txp1035 commented
主要是命令行代码用了umi-util，打包后全量导入了，log里面直接就创建文件夹了，我觉得应该调用log的方法时候去判断要不要创建文件夹
![image](https://user-images.githubusercontent.com/9554297/177225214-28eb43e1-88b4-4ec0-8338-6efbae943860.png)
![image](https://user-images.githubusercontent.com/9554297/177225237-1608c643-edc6-41da-8caf-1f44a85511d7.png)

2022-07-05 01:39 UTC, PeachScript commented on packages/utils/src/logger.ts
> +  init();
看看能不能用 pino 的 hooks 来代替 init：https://github.com/pinojs/pino/blob/master/docs/api.md#hooks-object

2022-07-05 01:39 UTC, PeachScript commented on packages/utils/src/logger.ts
> +  if (!fsExtra.pathExistsSync(loggerDir)) {
考虑用 flag 而不是 fs 来判断，减少文件系统访问次数

2022-07-05 03:44 UTC, fz6m commented
感觉还需要 find 一下。https://github.com/avajs/find-cache-dir

2022-07-05 03:53 UTC, fz6m commented
之前我在旧仓库实现过一版，看看对你有没有帮助：

https://github.com/umijs/umi-next/pull/891/files

2022-07-05 05:01 UTC, txp1035 commented
> https://github.com/avajs/find-cache-dir
之前我判断了路径的，考虑到文件开销更大就换标识了

2022-07-05 05:02 UTC, txp1035 commented
> 之前我在旧仓库实现过一版，看看对你有没有帮助：
> 
> https://github.com/umijs/umi-next/pull/891/files

我看说的是说命令行不用log，但是只要引入util就会执行创建文件了

2022-07-05 06:39 UTC, sorrycc commented
解的问题是什么，这个问题怎么复现？

2022-07-05 07:54 UTC, txp1035 commented
> 解的问题是什么，这个问题怎么复现？
运行yarn create umi app可以复现，前面两张图就是问题，会生成多余的node_modules文件夹

2022-07-05 09:33 UTC, PeachScript requested changes
目前的实现不够简洁，用 pino 的 [hooks](https://github.com/pinojs/pino/blob/master/docs/api.md#hooks-object) 或 @fz6m 提供的 proxy 方案实现吧

2022-07-05 09:40 UTC, txp1035 commented
> 目前的实现不够简洁，用 pino 的 [hooks](https://github.com/pinojs/pino/blob/master/docs/api.md#hooks-object) 或 @fz6m 提供的 proxy 方案实现吧

按照我们现在的思路pino还没有调用所以进不了钩子，@fz6m的代理已经很简洁了，但是我看现在prefixes会导出去如果外部使用，挂代理也不太好。

2022-07-06 11:08 UTC, txp1035 commented
> 

已经用了proxy了，导出的我去掉了，项目里面没有使用

2022-07-06 14:17 UTC, txp1035 commented
冗余的log
![image](https://user-images.githubusercontent.com/9554297/177571807-f12fdd93-e1c0-43bb-bc83-33edb713c41d.png)

2022-07-07 12:36 UTC, txp1035 commented
@PeachScript @sorrycc check下？

2022-07-13 03:22 UTC, txp1035 commented on packages/utils/src/logger.ts
> +export function error(...message: any[]) {
@PeachScript 看下呢

2022-07-13 18:16 UTC, txp1035 commented
![image](https://user-images.githubusercontent.com/9554297/178803007-6bd5c69b-0d91-4cde-913b-19e354cfbff7.png)
调试了下日志输出 @sorrycc

2022-07-13 18:53 UTC, txp1035 commented
![image](https://user-images.githubusercontent.com/9554297/178809030-039985bc-8205-4cd7-a299-d27a680a898f.png)
![image](https://user-images.githubusercontent.com/9554297/178809309-a992e7b6-739d-49dd-913e-81fe750a2926.png)
系统默认不能修改
customLevels参数应该是添加新记录可以加level，就像ready、event、wait @sorrycc .

2022-07-13 18:54 UTC, txp1035 commented
@sorrycc 要不要我把日志顺便优化一下，我最近在弄这个
![image](https://user-images.githubusercontent.com/9554297/178810009-24a65281-0202-407c-8421-59dbf7699035.png)

2022-07-14 02:27 UTC, sorrycc commented
1、更全更完善的日志指的是「补充更多日志内容」
2、这个 PR 变更的点我在 https://github.com/umijs/umi/pull/8512 的解了，这个先关了，感谢前期的贡献和讨论

2022-07-14 02:27 UTC, closed without merging

2022-07-14 07:01 UTC, fz6m commented
#8512 没解调用 `pnpm create umi project` 时，会在 `./` 创建 `node_modules` 的问题。

```bash
  pnpm create umi project
```

```bash
# after

.
├── node_modules # ← 这是非预期的
└── project
```

2022-07-16 05:53 UTC, txp1035 commented
> #8512 没解调用 `pnpm create umi project` 时，会在 `./` 创建 `node_modules` 的问题。
> 
> ```shell
>   pnpm create umi project
> ```
> 
> ```shell
> # after
> 
> .
> ├── node_modules # ← 这是非预期的
> └── project
> ```

我也试了一下，umi项目link是不生成的，直接通过npm就生成了

2022-07-16 06:16 UTC, txp1035 commented
![image](https://user-images.githubusercontent.com/9554297/179342661-2fe34de4-804b-4959-9e75-e9af35da3210.png)
重新build试了下确实存在，是不是得在用util那去配个环境？ @sorrycc

2022-07-16 06:27 UTC, txp1035 commented
> #8512 没解调用 `pnpm create umi project` 时，会在 `./` 创建 `node_modules` 的问题。
> 
> ```shell
>   pnpm create umi project
> ```
> 
> ```shell
> # after
> 
> .
> ├── node_modules # ← 这是非预期的
> └── project
> ```

npx cross-env FS_LOGGER='none'  create-umi a1232 大概是这个意思

2022-07-16 06:35 UTC, txp1035 commented
![image](https://user-images.githubusercontent.com/9554297/179343344-dcfa51d1-1bf2-414b-8aea-33548514b834.png)
是不是要在这里加一个环境啊 @sorrycc

2022-07-16 06:47 UTC, txp1035 commented
#8562