feat(bundler-webpack): support cacheDirectoryPath
umijs/umi pull request #8465
Opened 2022-07-07 13:56 UTC by July-ing

null

-----
[View rendered docs/docs/api/config.md](https://github.com/July-ing/umi/blob/feature/cacheDirectoryPath/docs/docs/api/config.md)

2022-07-08 13:18 UTC, July-ing commented on packages/bundler-webpack/src/dev.ts
> +      cacheDirectory: join(cacheDirectoryPath, 'bundler-webpack'),
我看cli里build是没有开启cache的 这次要一起开嘛

2022-07-08 17:15 UTC, July-ing commented on packages/bundler-webpack/src/dev.ts
> +      cacheDirectory: join(cacheDirectoryPath, 'bundler-webpack'),
明白了 感谢 已更新～

2022-07-11 09:09 UTC, sorrycc requested changes

2022-07-11 13:49 UTC, sorrycc approved these changes

2022-07-11 13:49 UTC, merged