feat(test): support test mock RenderClient
umijs/umi pull request #8493
Opened 2022-07-11 13:24 UTC by chenshuai2144

2022-07-12 07:50 UTC, sorrycc requested changes
1、感觉 export 的东西太多了，会影响后续 renderer-react 的内部调整
2、详细描述下这些东西暴露出去之后是怎么用的，应该有更好的方案

2022-07-12 07:50 UTC, sorrycc commented on packages/testing/src/index.ts
> +export const waitTime = (time: number) => {
这个不要加这里。

2022-07-12 07:50 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +      exports.push(`import { createPluginManager } from './core/plugin';`);
1、import 应该是 export ? 
2、用私有成员 `_createPluginManager`，这个方法不希望其他地方用

2022-07-12 08:17 UTC, chenshuai2144 commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +      exports.push(`import { createPluginManager } from './core/plugin';`);
🆗

2022-07-12 08:18 UTC, chenshuai2144 commented on packages/testing/src/index.ts
> +export const waitTime = (time: number) => {
这个还挺常用的，想搞个出来

2022-07-20 02:50 UTC, chenshuai2144 commented
不删除编译不过去了，有些库太老不支持 node 中 render

2022-10-19 08:39 UTC, closed without merging