feat(plugins): layout menu support routes wrappers conf
umijs/umi pull request #8509
Opened 2022-07-12 18:35 UTC by xierenyuan

Close #8497

解决layout 插件同 路由wrappers 使用冲突

2022-07-13 04:03 UTC, fz6m commented on packages/plugins/src/layout.ts
> +    const newRoute = {...route}
```suggestion
    const newRoute = { ...route }
```

2022-07-13 04:15 UTC, sorrycc requested changes

2022-07-13 04:15 UTC, sorrycc commented on packages/core/src/route/routesConfig.ts
> +    opts.memo.ret[id].menuPath = opts.route.path;
menuPath 改用 originPath 吧，虽然是给 layout 用的，但命名不和插件耦合。

2022-07-13 04:44 UTC, sorrycc approved these changes

2022-07-13 04:44 UTC, merged

2022-08-07 19:43 UTC, drizzlesconsin commented
wrappers 还会和 `layout: false` 冲突。

当加上 wrappers 控制页面访问权限，`layout: false` 的配置失效。

@fz6m @xierenyuan

2022-08-08 06:46 UTC, fz6m commented
给最小复现看看

2022-08-08 07:35 UTC, drizzlesconsin commented
@fz6m 已更新 [umi4-issue-mini-example](https://github.com/drizzlesconsin/umi4-issue-mini-example)

https://github.com/umijs/umi/issues/8315#issuecomment-1207472402