feat(mfsu): mfsu support exclude of some package
umijs/umi pull request #8543
Opened 2022-07-14 14:52 UTC by xierenyuan

mfsu 支持通过配置排除某些包
支持 正则匹配 因为 走了 babel-plugin-import 后 文件变得很碎

2022-07-15 03:20 UTC, fz6m commented on packages/bundler-webpack/src/schema.ts
> +          exclude: Joi.array().items(Joi.any()),
```suggestion
          exclude: Joi.array().items(Joi.alternatives().try(Joi.string(), Joi.object().regex())),
```

2022-07-15 08:01 UTC, sorrycc requested changes

2022-07-15 08:01 UTC, sorrycc commented on docs/docs/api/config.md
> +- `exclude` 手动排除某些不需要被 MFSU 处理的依赖, 比如 `vant` 不希望走 MFSU 处理 可以配置 `{ exclude: [ 'vant' ] }`
前面类型描述里需要加下 exclude 。

2022-07-18 04:26 UTC, sorrycc approved these changes

2022-07-18 04:26 UTC, merged