fix: app.ts 编译报错信息模糊
umijs/umi pull request #8714
Opened 2022-07-26 16:30 UTC by stormslowly

2022-07-26 17:40 UTC, fz6m commented on packages/bundler-utils/src/index.ts
> +    column: number;
```suggestion
    line?: number;
    column?: number;
```

2022-07-27 00:29 UTC, stormslowly commented on packages/bundler-utils/src/index.ts
> +    column: number;
```ts
type Errors = {
  location?: {
    line: number;
    column: number;
  };
  text: string;
}[];
```

2022-07-27 02:16 UTC, sorrycc requested changes
code-frame 在 bundles/babel/packages/code-frame 里已经有了。

2022-07-27 02:18 UTC, sorrycc commented on packages/bundler-utils/src/index.ts
> +  for (let error of errors) {
```suggestion
  for (const error of errors) {
```

2022-07-27 03:30 UTC, stormslowly commented
> code-frame 在 bundles/babel/packages/code-frame 里已经有了。

已经替换

2022-07-27 04:29 UTC, sorrycc approved these changes

2022-07-27 04:29 UTC, merged