fix: 修复 plugin-locale formatMessage的bug
umijs/umi pull request #8759
Opened 2022-07-28 09:00 UTC by YdreamW

2022-07-29 01:41 UTC, sorrycc commented
1、代码风格不对，没有做 prettier
2、标题要说明是修改了具体什么 BUG，方便后续写 Changelog 的同学

2022-07-29 01:41 UTC, sorrycc requested changes
1、代码风格不对，没有做 prettier
2、标题要说明是修改了具体什么 BUG，方便后续写 Changelog 的同学

2022-07-29 02:20 UTC, merged

2022-09-05 08:40 UTC, viewweiwu commented
3.x 好像也有这个问题，考虑在 3.x 上面处理吗

2022-09-05 08:43 UTC, viewweiwu commented
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/14287892/188407422-9013b596-6c30-42a3-b6bf-40779b35acdd.png">

2022-09-05 09:11 UTC, viewweiwu commented
这个 plugin 什么时候发布
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/14287892/188413292-fe1de647-d26d-4b28-a1c9-eb68c451bf71.png">