feat: add defineApp
umijs/umi pull request #8802
Opened 2022-08-01 06:45 UTC by zenotsai

实现思路：

插件约定输出一个 `runtimeConfig.d.ts` 作为插件的运行时配置
通过动态生成 `defineApp` ，使用交叉类型合并所有插件导出的运行时配置

修改点：
1，为自带的 layout、dva、qiankun 添加` runtimeConfig.d.ts `生成逻辑
2，在 tmpFile 中生成 `defineApp`，添加了一个 `defineApp.tpl `用于生成代码
3，修改了 `plugin.tpl`，添加了一个 __defaultExport 用于处理 `export default `的场景

2022-08-01 06:55 UTC, xiaohuoni commented on docs/docs/api/runtime-config.md
> +如果你想在写配置时也有提示，可以通过 umi 的 defineApp 方法定义配置，
感觉能不能直接支持之前的写法，感觉用户运行时配置，不太会写 defineApp。
我想要的效果，类似：
```
/** @type {import('umi').RuntimeConfig} */
expoprt const layout = { }
```

2022-08-01 08:29 UTC, fz6m commented on packages/umi/index.d.ts
> +export * from './constants'
不需要这一行吧？

2022-08-01 08:35 UTC, fz6m commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +        'export type PluginRunTimeConfig = PluginDefaultRuntimeConfig';
这里有 `runTime` / `RunTime` / `Runtime` ，大小写建议统一一下。

2022-08-01 08:38 UTC, fz6m commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +          join(api.paths.absTmpPath, plugin, 'runtimeConfig.d.ts'),
这里 `runtimeConfig.d.ts` 这个字符串，在 umi 这个包里导出了，又重复写了一遍，没有完整的复用性。

提供一个写 runtime type 的 api，收敛起来这个值，也不用导出了，会不会更好？

2022-08-01 08:43 UTC, fz6m commented on packages/plugins/src/dva.ts
> +        export default RunTimeDvaConfig;
左边留白，这样输出出来的文件内容会比较丑，去掉左边的空格会不会更好

2022-08-01 08:49 UTC, fz6m commented on packages/preset-umi/templates/plugin.tpl
> +function __defaultExport (obj) {
这个 `export default` 的场景需求的来源是啥，貌似现在所有的插件都没有 `export default` 这个情况，对用户来说是一种预期外的副作用吧 🤔

2022-08-01 09:04 UTC, fz6m commented on docs/docs/api/runtime-config.md
> +如果你想在写配置时也有提示，可以通过 umi 的 defineApp 方法定义配置，
这里用：

```ts
export const layout: IRuntimeLayoutConfig = {
  // ...
}
```

会不会更好？

实现思路：

统一导出的 interface name ：`IRuntimeConfig`，示例：

```ts
// .umi/plugin-layout/runtimeConfig.d.ts

export interface IRuntimeConfig {
  // ...
}
```

```ts
// exports.ts

import type { IRuntimeConfig as I${
  lodash.upperCase(
    lodash.camelCase(this.plugin.key)
  )
}RuntimeConfig } from './plugin-layout/runtimeConfig.d'

export ↑
```

2022-08-02 11:34 UTC, zenotsai commented on packages/preset-umi/templates/plugin.tpl
> +function __defaultExport (obj) {
现在会有这种情况
`
// app.ts
import { defineApp } from 'umi'


export default defineApp({
  // 运行时配置
})
`
我加了个判断，只针对 app.ts 处理，避免对用户造成困扰

2022-08-02 11:35 UTC, zenotsai commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +          join(api.paths.absTmpPath, plugin, 'runtimeConfig.d.ts'),
开发时也在纠结，但是感觉这个复用的只有 这个文件名而已，直接写个 api.writeRuntimeConfig 感觉有点多余

2022-08-02 11:36 UTC, zenotsai commented on packages/umi/index.d.ts
> +export * from './constants'
done

2022-08-02 11:39 UTC, zenotsai commented on docs/docs/api/runtime-config.md
> +如果你想在写配置时也有提示，可以通过 umi 的 defineApp 方法定义配置，
@xiaohuoni 已支持

在 js 中支持这样配置

![image](https://user-images.githubusercontent.com/12895975/182365660-9538265e-8a7d-4af5-b692-bbb371e40253.png)


TypeScript
![image](https://user-images.githubusercontent.com/12895975/182365835-ad5aebfd-0b45-4334-a114-cd766bee4322.png)

2022-08-02 11:47 UTC, zenotsai commented on docs/docs/api/runtime-config.md
> +如果你想在写配置时也有提示，可以通过 umi 的 defineApp 方法定义配置，
@fz6m 好主意，但是我有个顾虑，现在 plugin key 没做任何限制，如果写了 ```666Umi```  这种数字开头的 key ，并不符合 js 命名规范

 现在也能这么写，就是有点丑。。。
```typescript
import {  RuntimeConfig } from 'umi'

export const layout: RuntimeConfig['layout'] = () => {
  return {
    title: 'umi'
  }
}
```

2022-08-02 11:57 UTC, fz6m commented on docs/docs/api/runtime-config.md
> +如果你想在写配置时也有提示，可以通过 umi 的 defineApp 方法定义配置，
你说得对，现在 `RuntimeConfig['layout']` 折中应该是比较好的了。

2022-08-02 12:00 UTC, fz6m commented on docs/docs/api/runtime-config.md
> +})
这里补充一下单独使用的文档呗。

```ts
import { RuntimeConfig } from 'umi'

export const layout: RuntimeConfig['layout'] = {}
```

2022-08-03 07:56 UTC, sorrycc requested changes

2022-08-03 07:56 UTC, sorrycc commented on packages/plugins/src/qiankun/slave.ts
> +      path: RUNTIME_TYPE_FILE_NAME,
qiankun 既开 master 又开 slave 时会冲突吗？

2022-08-03 07:56 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +          hasDefaultExport: appPluginRegExp.test(plugin),
加个注释，说明为啥处理 app.ts 允许包含 export default。

2022-08-03 07:56 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +
额外空行不要加，by design。

2022-08-03 07:56 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +      exports.push(`export * from './core/defineApp'`);
```suggestion
      exports.push(`export { defineApp } from './core/defineApp'`);
```

2022-08-03 07:56 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +      exports.push(`export * from './core/defineApp'`);
```suggestion
      exports.push(`export { defineApp } from './core/defineApp'`);
```

具名导出，不要用 * 。

2022-08-03 07:56 UTC, sorrycc commented on packages/preset-umi/src/features/tmpFiles/tmpFiles.ts
> +          pluginIndex++;
```suggestion
          pluginIndex += 1;
```

2022-08-03 07:56 UTC, sorrycc commented on packages/preset-umi/templates/defineApp.tpl
> +
```suggestion
```

不要多余无意义的空行。

2022-08-03 07:56 UTC, sorrycc commented on packages/umi/src/index.ts
> +export * from './constants';
```suggestion
export { RUNTIME_TYPE_FILE_NAME } from './constants';
```

具名导出，不用 * 。

2022-08-03 09:47 UTC, zenotsai commented on packages/plugins/src/qiankun/slave.ts
> +      path: RUNTIME_TYPE_FILE_NAME,
看起来是支持的

// plugins/libs/qiankun/slave/lifecycles.ts

![image](https://user-images.githubusercontent.com/12895975/182578623-a9c57535-e303-48d7-9958-bc5d8f031cda.png)

2022-08-03 11:54 UTC, fz6m commented on docs/docs/api/runtime-config.md
> +import {  RuntimeConfig } from 'umi'
```suggestion
import { RuntimeConfig } from 'umi'
```

2022-08-03 11:54 UTC, fz6m commented on packages/preset-umi/templates/defineApp.tpl
> +  rootContainer?: (lastRootContainer:JSX.Element, args?: any) => void;
```suggestion
  rootContainer?: (lastRootContainer: JSX.Element, args?: any) => void;
```

2022-08-04 08:00 UTC, sorrycc approved these changes

2022-08-04 08:00 UTC, merged