Fix/mf apply hmr
umijs/umi pull request #8805
Opened 2022-08-01 07:44 UTC by kevinpursuing

umi bundler webpack的hmr在module federation暴露的模块中失效
以下改动针对所有出口文件，新增hmr

2022-08-01 07:49 UTC, kevinpursuing commented
> umi bundler webpack的hmr在module federation暴露的模块中失效 以下改动针对所有出口文件，新增hmr

实现思路：
参考 [webpack-dev-server](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js)
wds在对于module federation等的入口文件基于EntryPlugin进行了ws注入
这样在host端使用时同样可以使用remote端的热更

2022-08-01 09:21 UTC, fz6m commented on packages/bundler-webpack/src/config/config.ts
> +    await addAdditionEntryPlugin(applyOpts);
这个写在 mf 插件那边会不会更好？

2022-08-01 09:21 UTC, fz6m commented on packages/bundler-webpack/src/config/additionalEntryPlugin.ts
> +      return;
这个逻辑有啥用么

2022-08-01 09:22 UTC, fz6m commented on packages/bundler-webpack/src/config/additionalEntryPlugin.ts
> +        context: compiler.context,
下面没用到 `this.options` ，这个的意义是啥

2022-08-01 09:32 UTC, kevinpursuing commented on packages/bundler-webpack/src/config/config.ts
> +    await addAdditionEntryPlugin(applyOpts);
mf插件仅在.umirc中有mf配置的时候才生效是吗，如果使用chainwebpack，这个插件就不生效了吧

2022-08-03 07:31 UTC, sorrycc requested changes

2022-08-03 07:31 UTC, sorrycc commented on packages/bundler-webpack/src/config/additionalEntryPlugin.ts
> +      if (typeof EntryPlugin !== 'undefined') {
EntryPlugin 啥时候会 undefined？如果不会 undefined，那就不用加判断。

2022-08-03 07:31 UTC, sorrycc commented on packages/bundler-webpack/src/config/additionalEntryPlugin.ts
> +          new EntryPlugin(compiler.context, additionalEntry, {
https://github.com/umijs/umi/blob/94449642dccd1e0107a3dee992ea7eb92894aef7/packages/bundler-webpack/src/config/config.ts#L92
和这里添加的会不会重复了？如果这里的改动可以覆盖所有 entry，那可以把上面的删了。

2023-07-24 09:00 UTC, wenghongtian commented
这个pr没人看了吗

2023-12-21 01:40 UTC, WhatIsSpark commented
请问下目前这个问题什么进度
或者我们该如何处理这个问题

2023-12-21 17:33 UTC, fz6m commented
由于 mf 作者表示 mf 的下一个版本即将进行大改，故不推荐继续使用现有的 mf 功能，因为这会造成很严重的历史债务。

2024-01-04 02:04 UTC, WhatIsSpark commented
是不是有口子可以不使用mf，使用webpack-dev-server来解决这个问题？

2024-01-07 03:18 UTC, WhatIsSpark commented
> 由于 mf 作者表示 mf 的下一个版本即将进行大改，故不推荐继续使用现有的 mf 功能，因为这会造成很严重的历史债务。

是否可以绕过umi自带的mf，使用webpack的方式，我们用户自行来解决这个问题？

2024-01-09 03:25 UTC, fz6m commented
如需使用原生 mf 的方式，请自行修改 umi 的 webpack 配置，并编写插件修改 umi 入口文件，之后自行探索 mf 的实际行为，使用 mf 基本上只有这两步需要改，可以无需使用 umi 的 mf 插件。

如果涉及到 dev server ，可以自行修改 umi 的 express ，通过插件的 `api.onBeforeMiddleware` 方法就可以拿到 express app 了，之后如果想做什么调整自行修改即可。

2024-01-14 09:25 UTC, WhatIsSpark commented
没事，解决了，感谢回复
---- Replied Message ----
| From | ***@***.***> |
| Date | 01/09/2024 11:26 |
| To | umijs/umi ***@***.***> |
| Cc | 十年人间 ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [umijs/umi] fix: mf apply hmr (PR #8805) |

如需使用原生 mf 的方式，请自行修改 umi 的 webpack 配置，并编写插件修改 umi 入口文件，之后自行探索 mf 的实际行为，使用 mf 基本上只有这两步需要改，可以无需使用 umi 的 mf 插件。

如果涉及到 dev server ，可以自行修改 umi 的 express ，通过插件的 api.onBeforeMiddleware 方法就可以拿到 express app 了，之后如果想做什么调整自行修改即可。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

2024-11-26 12:55 UTC, closed without merging