docs: fix search
umijs/umi pull request #8926
Opened 2022-08-09 15:25 UTC by txp1035

背景：在用搜索功能搜索关键词找文档，挨个查阅的时候发现无效连接
![image](https://user-images.githubusercontent.com/9554297/183690782-c4b9dc49-768c-4b1c-aa68-68069f9062a5.png)

2022-08-09 15:27 UTC, txp1035 commented
测试了docs插件的search方法，发现路由生成包含了两种
![iShot2022-08-09 22 48 42](https://user-images.githubusercontent.com/9554297/183691196-8142489a-136f-4be8-9e4d-7189e41f3969.png)

2022-08-09 15:54 UTC, txp1035 commented
修改后效果
![image](https://user-images.githubusercontent.com/9554297/183699883-8921bd88-09f8-4204-a65b-6dee03ba93f0.png)

2022-08-30 07:29 UTC, sorrycc requested changes

2022-08-30 07:29 UTC, sorrycc commented on packages/plugin-docs/client/theme-doc/Search.tsx
> +  Object.keys(routes).forEach((path) => {
只处理这里就好了，zh-CN.json 及相关的不要改动。

2022-08-31 02:48 UTC, sorrycc approved these changes

2022-08-31 02:48 UTC, merged