fix(preset-umi): mock hmr don't work in win (#8882)
umijs/umi pull request #8927
Opened 2022-08-10 02:01 UTC by liangskyli

#8882
windows下，测试基础热更新正常

2022-08-10 03:35 UTC, sorrycc commented
/ 改成 \ 很奇怪，非 win 下就跑不了了。得找下 \ 的路径啥时候设进去的。

2022-08-10 03:35 UTC, sorrycc requested changes
/ 改成 \ 很奇怪，非 win 下就跑不了了。得找下 \ 的路径啥时候设进去的。

2022-08-10 04:52 UTC, liangskyli commented
没有mac, 没测试过mac,  这里判断系统处理?

2022-08-10 05:18 UTC, liangskyli commented
https://webpack.docschina.org/api/module-methods/#requirecache

```ts
var d1 = require('dependency');
require('dependency') === d1;
delete require.cache[require.resolve('dependency')];
require('dependency') !== d1;
```
windows下，require.resolve('dependency') 是\，require.cache key设置缓存应该是webpack5里做的处理

2022-08-10 05:31 UTC, liangskyli commented
@sorrycc 改了，再看下，mac 应该没问题了

2022-08-10 05:57 UTC, liangskyli commented
改用require.resolve

2022-08-11 06:32 UTC, sorrycc commented on packages/preset-umi/src/features/mock/getMockData.ts
>        const mockFile = winPath(`${opts.cwd}/${file}`);
const mockFile = join(opts.cwd, file);

再试试是不是这行改用 join 就可以了？下面不用 require.resolve。

2022-08-11 08:08 UTC, liangskyli commented
join确实可以





------------------ Original ------------------
From: chencheng (云谦) ***@***.***&gt;
Date: Thu,Aug 11,2022 2:32 PM
To: umijs/umi ***@***.***&gt;
Cc: liangsky ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [umijs/umi] fix(preset-umi): mock hmr don't work in win (#8882)(PR #8927)





 
@sorrycc commented on this pull request.
 
 
In packages/preset-umi/src/features/mock/getMockData.ts:
 &gt; @@ -38,7 +38,7 @@ export function getMockData(opts: {        const mockFile = winPath(`${opts.cwd}/${file}`);  
const mockFile = join(opts.cwd, file);
 
再试试是不是这行改用 join 就可以了？下面不用 require.resolve。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-08-11 10:18 UTC, sorrycc commented on packages/preset-umi/src/features/mock/getMockData.ts
> +import { join } from "path";
```suggestion
import assert from 'assert';
import { join } from 'path';
import { DEFAULT_METHOD, MOCK_FILE_GLOB, VALID_METHODS } from './constants';
```

2022-08-11 10:19 UTC, sorrycc approved these changes

2022-08-11 10:19 UTC, merged