优化 scripts 配置项文件插入位置，在 umi.js 之前；支持 Automatic publicPath
umijs/umi pull request #8983
Opened 2022-08-16 05:18 UTC by huarse

1. 4.0.9 的时候有一个 [PR](https://github.com/umijs/umi/pull/8647) 优化了 umi.css 的顺序，但是 js 的顺序仍然是放到前面，也会有问题，在 3.x  的时候主文件也是一直是注入到最后的
2. `publicPath` 设置为 'auto' 后，加载 chunk 文件会根据当前的主文件 host 去匹配，这一点在前后端分离并区分CDN环境的情况下非常有用，webpack 也很早就支持了 [Automatic publicPath](https://webpack.js.org/guides/public-path/#automatic-publicpath)

2022-08-16 06:36 UTC, sorrycc requested changes
第一点是 by design 的，属于 3 到 4 的 break change，在 4 的大版本中不做调整。

2022-08-16 06:43 UTC, huarse commented
> 第一点是 by design 的，属于 3 到 4 的 break change，在 4 的大版本中不做调整。

虽然还是不太理解这个 break change，不过这一点可以通过自定义插件解决，也能接受；

2022-08-16 07:37 UTC, sorrycc commented on packages/preset-umi/src/features/configPlugins/schema.ts
> +        .regex(/(\/|auto)$/)
这个正则还有点问题，不是「以 auto 开始」，而是「就是 auto」

2022-08-16 07:48 UTC, sorrycc approved these changes

2022-08-16 07:49 UTC, merged

2022-08-16 07:50 UTC, huarse commented on packages/preset-umi/src/features/configPlugins/schema.ts
> +        .regex(/(\/|auto)$/)
😂 啊这里我确实偷懒了，不好意思，已经改掉了

2022-08-18 02:13 UTC, ayahua commented
这个改动还没发布是吗？现在的话，前后端分离并区分CDN环境的情况是要怎么解决啊？

2022-09-07 01:14 UTC, Renderz commented on packages/preset-umi/src/commands/dev/getAssetsMap.ts
> +  const displayPublicPath = publicPath === 'auto' ? '/' : publicPath;
请问这里auto之后publicPath是'/'和直接配置'/'有什么区别呢？
auto如果是基于index.html路径加载资源文件，不是应该配置成'./'么？

2022-09-08 07:25 UTC, huarse commented on packages/preset-umi/src/commands/dev/getAssetsMap.ts
> +  const displayPublicPath = publicPath === 'auto' ? '/' : publicPath;
- 这个 feature 最重要的是让 webpack 开启支持 [Automatic publicPath](https://webpack.js.org/guides/public-path/#automatic-publicpath) ，这个特性在HTML / JS 资源分离的模式下（比如 HTML 是由 java vm 渲染，JS 上传到CDN上 ）非常有用

- 你这里是 `publicPath ` 的另一处使用，影响的是注入到 HTML 中的文件路径，这个地方是不能使用 auto 的（否则注入文件的逻辑会出BUG），原本考虑为这里再加一个配置项，但增加一个配置项会带来更多的理解成本，所以就在这里把 auto 手动修正为默认值 '/' ，本地运行也是OK的，如果需要修改，推荐使用自定义插件能力修改，例如：


```ts
api.modifyHTML(($) => {
  // 也可以通过 process.env 中的环境变量判断
  const injectionPublicPath = 'http://127.0.0.1:8888/';

  // 手动修改 umi.js 和 umi.css 的 host
  $('body script[src]').each((_, el) => {
    const $el = $(el);
    if (/umi/.test($el.attr('src')!)) {
      $el.attr('src', `${injectionPublicPath}umi.js`);
    }
  });
  $('head link[rel="stylesheet"]').each((_, el) => {
    const $el = $(el);
    if (/umi/.test($el.attr('href')!)) {
      $el.attr('href', `${injectionPublicPath}umi.css`);
    }
  });
  return $;
});
```