[wip]feat(plugin-run): init
umijs/umi pull request #9014
Opened 2022-08-17 13:25 UTC by txp1035

2022-08-17 16:20 UTC, txp1035 commented
## 背景
考虑到用户可能没有esno，使用pirates+esbuild执行脚本
## 错误记录
![image](https://user-images.githubusercontent.com/9554297/185191371-34b2bd6f-2450-4a3f-a981-165b2643bd0d.png)
![image](https://user-images.githubusercontent.com/9554297/185190628-c4fe97fc-3c9e-428c-8877-ec2e680367e0.png)
使用esbuild出错，切到cjs可以用

2022-08-18 09:44 UTC, sorrycc commented on packages/plugin-run/src/index.ts
> +      const runGlobals: string[] = api?.config?.run?.globals || [];
```suggestion
      const runGlobals: string[] = api.config.run?.globals || [];
```

2022-08-18 09:44 UTC, sorrycc commented on packages/plugin-run/src/index.ts
> +function winJoin(...args: string[]) {
winJoin 不需要，应该不存在 windows 兼容问题

2022-08-18 09:44 UTC, sorrycc commented on packages/plugin-run/src/index.ts
> +      const str = fsExtra.readFileSync(sourcePath);
sourcePath 内容不要读出来，直接加一个 `import '${sourcePath}'` 就好

2022-08-18 09:45 UTC, sorrycc commented on packages/plugin-run/src/index.ts
> +    const pkgPath = join(__dirname, '../node_modules/tsx/package.json');
```suggestion
    const pkgPath = require.resolve('tsx/package.json');
```

2022-08-18 09:46 UTC, sorrycc commented on packages/plugin-run/src/index.ts
> +    throw new Error(`tsx not found, please install it first.`);
tsx 包是依赖，肯定存在，不需要加 try...catch 。

2022-08-18 09:46 UTC, sorrycc commented on packages/plugin-run/src/index.ts
> +      const absSrcPath =
直接用 api.absSrcPath

2022-08-18 09:47 UTC, sorrycc commented on packages/plugin-run/src/index.ts
> +      const scriptPath = winJoin(absSrcPath, `.umi/plugin-run/${fileName}`);
.umi  目录的路径直接用 api.absTmpPath

2022-08-18 09:47 UTC, sorrycc commented on packages/plugin-run/src/index.ts
> +      const cwd = process.cwd();
cwd 用 api.cwd。

2022-08-18 09:54 UTC, sorrycc requested changes
umi 包的改动都不要了，由于 zx 不需要包一层，不如直接让用户依赖 zx 好了

2022-08-18 10:19 UTC, txp1035 commented on packages/plugin-run/src/index.ts
> +    const pkgPath = join(__dirname, '../node_modules/tsx/package.json');
我试过这样获取，获取不到，会报错.
![image](https://user-images.githubusercontent.com/9554297/185372281-a3bb658d-729e-48c7-a63e-e1300011af2a.png)

2022-08-18 10:47 UTC, txp1035 commented on packages/plugin-run/src/index.ts
> +      const str = fsExtra.readFileSync(sourcePath);
我试了下里面的api
![image](https://user-images.githubusercontent.com/9554297/185377142-f16d973f-6a6c-49c9-a61f-64f78c7b48f6.png)
没有可以直接加文件的选项啊

2022-08-18 10:52 UTC, txp1035 commented
![image](https://user-images.githubusercontent.com/9554297/185377888-cf1ee554-374c-4cf0-a615-a7ba2024cdc1.png)
有个点，这里是直接配置包名好还是配置导入语句，如果配置包名应该加个验证，要不用户建个js文件注入个import就很奇怪，而且zx也不能用require导入7是esm，4应该可以。

2022-08-18 10:56 UTC, txp1035 commented on packages/plugin-run/src/index.ts
> +      const scriptPath = winJoin(absSrcPath, `.umi/plugin-run/${fileName}`);
用了api.paths.absTmpPath

2022-08-18 10:59 UTC, txp1035 commented
> umi 包的改动都不要了，由于 zx 不需要包一层，不如直接让用户依赖 zx 好了

处理了，不过我想了下用户得自己装zx，要不用不了啊。umi内置直接能用才符合推广思路？

2022-08-18 14:58 UTC, sorrycc requested changes

2022-08-18 14:58 UTC, sorrycc commented on packages/plugin-run/src/index.ts
> +        tplPath: sourcePath,
tplPath 应该不需要传吧。

2022-08-19 11:01 UTC, fz6m commented on packages/plugin-run/src/index.ts
> +        content: `${runGlobals.map((item) => `import '${item}'\n`)}${str}`,
用户可能导入相对的东西或者包，不能这样把他的内容写过来吧。

2022-08-19 11:03 UTC, fz6m commented on examples/umi-run/.umirc.ts
> +    globals: ['zx/globals'],
用户应该自己导入 `zx/globas` ，否则获得不到全局的方法类型提示。可以给 zx 包起来提供：

```ts
import 'umi/run-globas' // 等价于 import 'zx/globals'
```

2022-08-19 11:04 UTC, fz6m commented on packages/plugin-run/src/index.ts
> +    throw new Error('Only typescript files can be run');
实际上 `node index.js` 时，没有明确指定 esm 的 package，仍将以 cjs 方式运行，所以 `.js` 的脚本也应该支持 🤔

2022-08-22 03:14 UTC, sorrycc commented on examples/umi-run/.umirc.ts
> +    globals: ['zx/globals'],
这个看用户自己的选择了，类型问题可以在 typigns.d.ts 里声明解决。

2022-08-22 03:15 UTC, sorrycc commented on packages/plugin-run/src/index.test.ts
> +});
```suggestion
test('check', () => {
  const t = () => {
    check('a.js');
  };
  expect(t).toThrow('Only typescript files can be run');
  expect(check('a.ts')).toBe(undefined);
});

test('getBinPath', () => {
  expect(getBinPath()).toBe(join(__dirname, '../node_modules/tsx/dist/cli.js'));
});

test('getFileNameByPath', () => {
  expect(getFileNameByPath('/a/b/c.ts')).toBe('c.ts');
});
```

2022-08-22 03:16 UTC, sorrycc approved these changes
合完我再微调下。

2022-08-22 03:16 UTC, merged