feat(antd): support antd@5
umijs/umi pull request #9044
Opened 2022-08-20 17:15 UTC by chenshuai2144

2022-08-21 02:29 UTC, chenshuai2144 commented on packages/plugins/src/antd.ts
> +        ...theme,
这里好像没生效是为什么？

2022-08-22 02:21 UTC, xiaohuoni commented
@chenshuai2144 antd 5 太试验性了吧？单独发一个包？

2022-08-22 04:10 UTC, chenshuai2144 commented
这个没有用antd@5 的特性，只是让能跑起来

2022-08-23 13:53 UTC, sorrycc requested changes

2022-08-23 13:53 UTC, sorrycc commented on packages/plugins/package.json
> +    "@ant-design/pro-components": "^2.0.0",
这个有 break change 吗？

2022-08-23 13:53 UTC, sorrycc commented on packages/plugins/src/layout.ts
> +    return dirname(require.resolve('@ant-design/pro-components/package.json'));
这是个 break change，会让现有声明了 @ant-design/pro-layout 依赖的用户失效。

2022-08-23 14:32 UTC, chenshuai2144 commented on packages/plugins/src/layout.ts
> +    return dirname(require.resolve('@ant-design/pro-components/package.json'));
@ant-design/pro-components 里面也安装了 @ant-design/pro-layout 应该能找到把

2022-08-23 14:34 UTC, sorrycc commented on packages/plugins/package.json
> +    "@ant-design/pro-components": "^2.0.0",
那还是别改了，有潜在 break change 的最后总是会产生 break change。

2022-08-23 14:36 UTC, chenshuai2144 commented
改了一默认的模板，改成了以 @ant-design/pro-components 为核心

2022-08-23 14:53 UTC, chenshuai2144 commented
好的

2022-08-23 15:00 UTC, chenshuai2144 commented on packages/plugins/package.json
> +    "@ant-design/pro-components": "^2.0.0",
去掉了

2022-08-24 02:04 UTC, sorrycc approved these changes

2022-08-24 02:04 UTC, merged

2023-01-04 05:55 UTC, liuxi0811 commented
> 做了以下几件事情
> 
> * antd@5 的情况下关掉 babel-import
> * 如果用了 antd@4 但是用了 antd@5 ，导入以下 antd.less
> * 如果用了 antd@5，为less 提供默认变量，防止项目挂掉
> * 如果antd@5 ，删除代码 layout 的  less 导入

遇到同样问题 后面如何解决的