docs(do-you-know): 📝 添加 do you know 条目
umijs/umi pull request #9205
Opened 2022-09-01 13:07 UTC by stormslowly

冲冲冲冲~

2022-09-01 13:10 UTC, PeachScript commented on did-you-know/package.json
> +      "text": "如果你需要使用 Pritter, %%frameworkCliName%% g prettier 就可以一键完成配置",
```suggestion
      "text": "如果你需要使用 Prettier, %%frameworkCliName%% g prettier 就可以一键完成配置",
```

2022-09-01 13:11 UTC, PeachScript commented on did-you-know/package.json
> +      "text": "如果你需要使用 DVA 来作为状态管理库, %%frameworkCliName%% g dva 就可以一键完成配置",
```suggestion
      "text": "如果你需要使用 DvaJS 来作为状态管理库, %%frameworkCliName%% g dva 就可以一键完成配置",
```

2022-09-01 13:22 UTC, fz6m commented on did-you-know/package.json
> +      "majorVersion": 4
```suggestion
    {
      "text": "COMPRESS=none umi build 可以关闭项目构建时的代码压缩功能, 方便调试项目的构建产物",
      "majorVersion": 4
    },
    {
      "text": "编写 src/loading.(jsx|tsx) 可以自定义页面的加载动画",
      "majorVersion": 4
    },
    {
      "text": "你知道可以通过 UMI_ENV 定义多个环境的配置吗",
      "url": "https://umijs.org/docs/guides/env-variables#umi_env",
      "majorVersion": 4
    },
    {
      "text": "想快速定制 html 模板、DIY 项目？试试编写项目级插件",
      "url": "https://umijs.org/docs/guides/directory-structure#plugints",
      "majorVersion": 4
```

2022-09-02 06:55 UTC, stormslowly commented on did-you-know/package.json
> +      "text": "如果想预览构建后产物, 可尝试新出的 %%frameworkCliName%% preview",
```suggestion
      "text": "如果想预览构建后产物, 可尝试 %%frameworkCliName%% preview",
```

2022-09-02 08:27 UTC, sorrycc commented on did-you-know/package.json
> +      "text": "COMPRESS=1 umi build 可以分析产物的源码构成",
这是啥功能？我咋不知道。。

2022-09-02 08:28 UTC, sorrycc requested changes
所有 umi 命令都需要换成 %%frameworkCliName%%。

2022-09-02 11:21 UTC, fz6m commented on did-you-know/package.json
> +      "text": "COMPRESS=1 umi build 可以分析产物的源码构成",
```suggestion
      "text": "ANALYZE=1 umi build 可以分析产物的源码构成",
```

2022-09-05 02:14 UTC, stormslowly commented on did-you-know/package.json
> +      "text": "ANALYZE=1 umi build 可以分析产物的源码构成",
```suggestion
      "text": "ANALYZE=1 %%frameworkCliName%% build 可以分析产物的源码构成",
```

2022-09-05 08:29 UTC, xiaohuoni commented
> 冲冲冲冲~

我在

2022-09-06 07:27 UTC, xiaohuoni approved these changes

2022-09-06 11:27 UTC, fz6m approved these changes

2022-09-19 02:53 UTC, sorrycc approved these changes

2022-09-19 02:53 UTC, merged