refactor: 🎨 node version < v16.9.0 , show config error directly
umijs/umi pull request #9315
Opened 2022-09-14 02:16 UTC by stormslowly

16.9.0 之前的 node 版本，不支持 cause ，所以真实的 error 打印不出来。

如果16.9.0 之前的直接抛错到下游。

2022-09-15 06:03 UTC, sorrycc requested changes

2022-09-15 06:03 UTC, sorrycc commented on packages/core/src/config/config.ts
> +          if (process.version < 'v16.9.0') {
应该不能直接这么比较版本吧。

2022-09-15 09:51 UTC, stormslowly commented on packages/core/src/config/config.ts
> +          if (process.version < 'v16.9.0') {
我错了

2022-09-19 02:44 UTC, sorrycc approved these changes

2022-09-19 02:44 UTC, merged