refactor(plugins-antd): 🎨 使用 antd5 禁用 antd.import
umijs/umi pull request #9552
Opened 2022-10-19 07:23 UTC by stormslowly

因为目录结构已经变了，不适用 babel-plugin-import 了

2022-10-19 08:23 UTC, sorrycc requested changes

2022-10-19 08:23 UTC, sorrycc commented on packages/plugins/src/antd.ts
> +        memo.antd.import = false;
主动抛错吧，引导用户删配置。

2022-10-20 08:27 UTC, sorrycc commented
跑一遍看看报错的样式是怎样的？感觉可能会有重复。

2022-10-21 01:52 UTC, stormslowly commented
![image](https://user-images.githubusercontent.com/415655/197092518-c2ec6f1a-1ade-4264-b795-686ba4cc106f.png)

2022-10-26 06:43 UTC, sorrycc commented
第一行的 fatal 报错不用，和下面的重复了。

2022-10-26 10:05 UTC, stormslowly commented
> 第一行的 fatal 报错不用，和下面的重复了。

已经删掉了

2022-11-03 07:36 UTC, sorrycc approved these changes

2022-11-03 07:36 UTC, merged