fix: sort models by deps
umijs/umi pull request #9846
Opened 2022-11-23 17:01 UTC by elivoa

fix sorting models by deps in plugin-model.

see also: [https://github.com/umijs/umi/issues/9837](https://github.com/umijs/umi/issues/9837)

2022-11-24 05:44 UTC, fz6m commented
写下单测吧，这个比较复杂。

2022-11-24 08:35 UTC, sorrycc requested changes
需要用例，这个肉眼看不出正确性，不敢合啊。

2022-11-24 15:40 UTC, elivoa commented
明天我加一些test进去。

2022-11-24 16:43 UTC, fz6m commented on packages/plugins/src/utils/modelUtils.ts
> +      `Duplicate namespace in models: ${graph
是否重复在前面有校验过了。

2022-11-24 16:47 UTC, fz6m commented on packages/plugins/src/utils/modelUtils.ts
> +    if (!zeronode) {
我理解这里没有 `zeronode` 且 `graph` 还有长度的时候就是出了循环依赖，可以抛错。前面的循环校验就不需要了。

2022-11-24 16:49 UTC, fz6m commented on packages/plugins/src/utils/modelUtils.ts
> +        node.in++;
当 `node.in !== node.deps.length` 的时候，其实是错误的依赖，应该抛错。

2022-11-24 16:55 UTC, fz6m commented on packages/plugins/src/utils/modelUtils.ts
> +  if (!n || !c) return;
代码里各种 `!n` / `!c` / `nn &` / `n &` 其实不需要，我们已经确定他肯定有了，而且都是对象了，必定是 true 。

2022-11-24 16:56 UTC, fz6m commented on packages/plugins/src/utils/modelUtils.ts
> +  const indexes: any = {}; // namespace -> Node
```suggestion
  const indexes: Record<string, TNode> = {}; // namespace -> Node
```

2022-11-24 16:56 UTC, fz6m commented on packages/plugins/src/utils/modelUtils.ts
> +  graph.forEach((node: TNode) => {
当可以自动推断的时候，不显示声明类型也可以，包括下面显示声明的位置，可以不声明，ts 会自动推断。

2022-11-24 16:58 UTC, fz6m commented on packages/plugins/src/utils/modelUtils.ts
> +    node.deps?.forEach((dep: string) => {
当使用 `deps?.` / `childs?.` 说明他可能没有，如果初始化了，说明他一定有，无需 `?.` 。同时，若使用 `?.` ，在 `TNode` 类型声明中应该是可选类型（ 如 `deps?: string[]` ），否则不应该使用 `?.` 。

2022-11-25 02:47 UTC, elivoa commented
@fz6m 多谢指教，上述问题均已修复，并付上test且自测通过。已经点了申请重新审查，不知道我操作的对不对。

2022-11-25 09:54 UTC, fz6m approved these changes

2022-11-25 09:54 UTC, fz6m commented
有多处需要变动，帮你改了下，感谢 PR 。

2022-11-30 03:06 UTC, elivoa commented
@fz6m 请问下目前这个PR的进度是怎样的？什么时候能合并并发tag？我的项目在等这个修复才能上线。

2022-12-01 07:33 UTC, sorrycc approved these changes

2022-12-01 07:33 UTC, merged