feat(preset-umi): codeSplitting support auto load chunk
umijs/umi pull request #9859
Opened 2022-11-24 13:09 UTC by xierenyuan

2022-11-24 13:17 UTC, xiaohuoni commented
@sorrycc 这个方案是来代替早上开会说的“把 chunks 加回来”

2022-11-24 13:53 UTC, sorrycc requested changes

2022-11-24 13:53 UTC, sorrycc commented on packages/preset-umi/src/features/codeSplitting/codeSplitting.ts
> +          const entryPointFiles = compilation.entrypoints
在 getAssetsMap.ts 里用 compilation.entrypoints 处理？因为放这里的话，用户自定义的 codeSplitting 就不生效了。

2022-11-25 03:23 UTC, xierenyuan commented on packages/preset-umi/src/features/codeSplitting/codeSplitting.ts
> +          const entryPointFiles = compilation.entrypoints
> 

好 晚上我更新一个版本

2022-12-02 08:27 UTC, sorrycc requested changes
想了下，webpack/webpack 在 dev 时增量构建时可能有问题，assets.js 和 assets.css 会累加。简单解可以是改成只针对 production 开启。

2022-12-02 08:43 UTC, xierenyuan commented
> 想了下，webpack/webpack 在 dev 时增量构建时可能有问题，assets.js 和 assets.css 会累加。简单解可以是改成只针对 production 开启。

调整完毕

2022-12-02 13:22 UTC, sorrycc approved these changes

2022-12-02 13:22 UTC, merged