feat(create-umi): add Sntd version Select
umijs/umi pull request #9918
Opened 2022-12-01 07:09 UTC by mysteryven

refer to: [更新 @umi/max 对 antd 的版本依赖为 >= 4.20.6 ](https://github.com/umijs/umi/issues/9906)

2022-12-01 10:21 UTC, fz6m commented on packages/create-umi/src/index.ts
> +const AntdV5 = '^5.0.0';
用枚举。

2022-12-01 15:13 UTC, fz6m commented on packages/create-umi/src/index.ts
> +            { title: 'V5 (^5.0.0)', value: EAntdVersion.V5 },
```suggestion
            { title: `V4 (${EAntdVersion.V4})`, value: EAntdVersion.V4 },
            { title: `V5 (${EAntdVersion.V5})`, value: EAntdVersion.V5 },
```

2022-12-02 07:59 UTC, sorrycc commented
改成用 antd 5 吧，用最新的稳定版，不要选了。

2022-12-02 07:59 UTC, sorrycc requested changes
改成用 antd 5 吧，用最新的稳定版，不要选了。

2022-12-05 03:00 UTC, sorrycc approved these changes

2022-12-05 03:00 UTC, merged